In [69]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/April 2026 Data Set/job-bank-open-data-all-job-postings-en-apr2026.csv",
    sep="\t",
    encoding="utf-16"
)

df.head()

df.shape

df.columns.tolist()

df.info()

for i, column in enumerate(df.columns):
    print(i, column)

df["Job Title"].value_counts().head(30)


data_jobs = df[
    df["Job Title"].str.contains(
        "data analyst|data scientist|business intelligence",
        case=False,
        na=False
    )
]

data_jobs.shape

data_jobs["Job Title"].value_counts()



data_jobs[
    ["Job Title", "Province/Territory", "City", "First Posting Date"]
].head(20)


data_jobs.shape


data_jobs["Job Title"].value_counts().head(30)

data_jobs["Province/Territory"].value_counts()

data_jobs["First Posting Date"].value_counts().sort_index()


for i, column in enumerate(df.columns):
    print(i, repr(column))


data_jobs.shape


data_jobs["Job Title"].value_counts()

<class 'pandas.DataFrame'>
RangeIndex: 53616 entries, 0 to 53615
Data columns (total 65 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   WIC Job Location Snapshot ID      53616 non-null  int64
 1   Job Title                         53616 non-null  str
 2   Original Job Title                20565 non-null  str
 3   NOC 2016 Code                     53315 non-null  float64
 4   NOC 2016 Code Name                53315 non-null  str
 5   NOC21 Code                        53317 non-null  float64
 6   NOC21 Code Name                   53317 non-null  str
 7   External Indicator                53616 non-null  int64
 8   First Posting Date                53616 non-null  str
 9   Vacancy Count                     53616 non-null  int64
 10  Official Language                 53616 non-null  str
 11  Education LOS                     21026 non-null  str
 12  Experience Level                  21026 non-null  str
 13  Government Type                   20716 non-null  str
 14  Placement Agency                  21026 non-null  str
 15  NAICS                             21026 non-null  str
 16  Province/Territory                53616 non-null  str
 17  City                              53124 non-null  str
 18  Work Location Postal Code         25013 non-null  str
 19  Economic  Region                  53124 non-null  str
 20  Various Location                  53616 non-null  str
 21  Employment Type                   51511 non-null  str
 22  Employment Term                   41486 non-null  str
 23  Employment Term Start Date        6004 non-null   str
 24  Employment Term End Date          487 non-null    str
 25  Employment Term Oncall            21026 non-null  str
 26  Employment Term Overtime          21026 non-null  str
 27  Employment Term Day               21026 non-null  str
 28  Employment Term Evening           21026 non-null  str
 29  Employment Term Shift             21026 non-null  str
 30  Employment Term Weekend           21026 non-null  str
 31  Employment Term Night             21026 non-null  str
 32  Employment Term Telework          21026 non-null  str
 33  Employment Term Early             21026 non-null  str
 34  Employment Term Flex              21026 non-null  str
 35  Employment Term Morning           21026 non-null  str
 36  Employment Term TBD               21026 non-null  str
 37  Salary Condition Detail           53607 non-null  str
 38  Salary Per                        53519 non-null  str
 39  Salary Minimum                    53606 non-null  float64
 40  Salary Maximum                    53606 non-null  float64
 41  Salary Condition Collective       21026 non-null  str
 42  Salary Condition Bonus            21026 non-null  str
 43  Salary Condition Disability       21026 non-null  str
 44  Salary Condition Gratuity         21026 non-null  str
 45  Salary Condition Medical          21026 non-null  str
 46  Salary Condition Mileage          21026 non-null  str
 47  Salary Condition Piecework        21026 non-null  str
 48  Salary Condition Commission       21026 non-null  str
 49  Salary Condition RESP             21026 non-null  str
 50  Salary Condition Dental           21026 non-null  str
 51  Salary Condition Group Insurance  21026 non-null  str
 52  Salary Condition Life Insurance   21026 non-null  str
 53  Salary Condition Pension          21026 non-null  str
 54  Salary Condition RRSP             21026 non-null  str
 55  Condition Vision Care             21026 non-null  str
 56  Salary Condition Other Benefits   21026 non-null  str
 57  Commission PER                    139 non-null    str
 58  Commission Type                   139 non-null    str
 59  Hours Per                         21026 non-null  str
 60  Hours Minimum                     24582 non-null  float64
 61  Hours Maximum                     24582 non-null  float64
 62  Work Hours                        53616 non-null  str
 63  Work Hours From Time              894 non-null    str
 64  Work Hours To Time                894 non-null    str
dtypes: float64(6), int64(3), str(56)
memory usage: 41.9 MB
0 WIC Job Location Snapshot ID
1 Job Title
2 Original Job Title
3 NOC 2016 Code
4 NOC 2016 Code Name
5 NOC21 Code
6 NOC21 Code Name
7 External Indicator
8 First Posting Date
9 Vacancy Count
10 Official Language
11 Education LOS
12 Experience Level
13 Government Type
14 Placement Agency
15 NAICS
16 Province/Territory
17 City
18 Work Location Postal Code
19 Economic  Region
20 Various Location
21 Employment Type
22 Employment Term
23 Employment Term Start Date
24 Employment Term End Date
25 Employment Term Oncall
26 Employment Term Overtime
27 Employment Term Day
28 Employment Term Evening
29 Employment Term Shift
30 Employment Term Weekend
31 Employment Term Night
32 Employment Term Telework
33 Employment Term Early
34 Employment Term Flex
35 Employment Term Morning
36 Employment Term TBD
37 Salary Condition Detail
38 Salary Per
39 Salary Minimum
40 Salary Maximum
41 Salary Condition Collective
42 Salary Condition Bonus
43 Salary Condition Disability
44 Salary Condition Gratuity
45 Salary Condition Medical
46 Salary Condition Mileage
47 Salary Condition Piecework
48 Salary Condition Commission
49 Salary Condition RESP
50 Salary Condition Dental
51 Salary Condition Group Insurance
52 Salary Condition Life Insurance
53 Salary Condition Pension
54 Salary Condition RRSP
55 Condition Vision Care
56 Salary Condition Other Benefits
57 Commission PER
58 Commission Type
59 Hours Per
60 Hours Minimum
61 Hours Maximum
62 Work Hours
63 Work Hours From Time
64 Work Hours To Time
0 'WIC Job Location Snapshot ID'
1 'Job Title'
2 'Original Job Title'
3 'NOC 2016 Code'
4 'NOC 2016 Code Name'
5 'NOC21 Code'
6 'NOC21 Code Name'
7 'External Indicator'
8 'First Posting Date'
9 'Vacancy Count'
10 'Official Language'
11 'Education LOS'
12 'Experience Level'
13 'Government Type'
14 'Placement Agency'
15 'NAICS'
16 'Province/Territory'
17 'City'
18 'Work Location Postal Code'
19 'Economic  Region'
20 'Various Location'
21 'Employment Type'
22 'Employment Term'
23 'Employment Term Start Date'
24 'Employment Term End Date'
25 'Employment Term Oncall'
26 'Employment Term Overtime'
27 'Employment Term Day'
28 'Employment Term Evening'
29 'Employment Term Shift'
30 'Employment Term Weekend'
31 'Employment Term Night'
32 'Employment Term Telework'
33 'Employment Term Early'
34 'Employment Term Flex'
35 'Employment Term Morning'
36 'Employment Term TBD'
37 'Salary Condition Detail'
38 'Salary Per'
39 'Salary Minimum'
40 'Salary Maximum'
41 'Salary Condition Collective'
42 'Salary Condition Bonus'
43 'Salary Condition Disability'
44 'Salary Condition Gratuity'
45 'Salary Condition Medical'
46 'Salary Condition Mileage'
47 'Salary Condition Piecework'
48 'Salary Condition Commission'
49 'Salary Condition RESP'
50 'Salary Condition Dental'
51 'Salary Condition Group Insurance'
52 'Salary Condition Life Insurance'
53 'Salary Condition Pension'
54 'Salary Condition RRSP'
55 'Condition Vision Care'
56 'Salary Condition Other Benefits'
57 'Commission PER'
58 'Commission Type'
59 'Hours Per'
60 'Hours Minimum'
61 'Hours Maximum'
62 'Work Hours'
63 'Work Hours From Time'
64 'Work Hours To Time'

Job Title
data scientist                            26
data analyst - informatics and systems    13
big data analyst                           3
business data analyst                      3
Name: count, dtype: int64

In [70]:
keywords = (
    "data analyst|"
    "data scientist|"
    "business intelligence|"
    "bi analyst|"
    "analytics analyst|"
    "data analytics|"
    "data quality analyst|"
    "reporting analyst"
)

data_jobs = df[
    df["Job Title"].str.contains(
        keywords,
        case=False,
        na=False
    )
]

data_jobs.shape

data_jobs["Job Title"].value_counts()

Job Title
data scientist                                       26
data analyst - informatics and systems               13
big data analyst                                      3
business data analyst                                 3
Strategic Business Planning and Reporting Analyst     1
data analytics manager                                1
Data Analytics Specialist                             1
Name: count, dtype: int64

In [71]:
jobs_clean = data_jobs[
    data_jobs["Job Title"].str.lower() != "data analytics manager"
].copy()

jobs_clean.shape

(47, 65)

In [72]:
for column in df.columns:
    print(column, "→", df[column].dtype)

WIC Job Location Snapshot ID → int64
Job Title → str
Original Job Title → str
NOC 2016 Code → float64
NOC 2016 Code Name → str
NOC21 Code → float64
NOC21 Code Name → str
External Indicator → int64
First Posting Date → str
Vacancy Count → int64
Official Language → str
Education LOS → str
Experience Level → str
Government Type → str
Placement Agency → str
NAICS → str
Province/Territory → str
City → str
Work Location Postal Code → str
Economic  Region → str
Various Location → str
Employment Type → str
Employment Term → str
Employment Term Start Date → str
Employment Term End Date → str
Employment Term Oncall → str
Employment Term Overtime → str
Employment Term Day → str
Employment Term Evening → str
Employment Term Shift → str
Employment Term Weekend → str
Employment Term Night → str
Employment Term Telework → str
Employment Term Early → str
Employment Term Flex → str
Employment Term Morning → str
Employment Term TBD → str
Salary Condition Detail → str
Salary Per → str
Salary Minimum → float64
Salary Maximum → float64
Salary Condition Collective → str
Salary Condition Bonus → str
Salary Condition Disability → str
Salary Condition Gratuity → str
Salary Condition Medical → str
Salary Condition Mileage → str
Salary Condition Piecework → str
Salary Condition Commission → str
Salary Condition RESP → str
Salary Condition Dental → str
Salary Condition Group Insurance → str
Salary Condition Life Insurance → str
Salary Condition Pension → str
Salary Condition RRSP → str
Condition Vision Care → str
Salary Condition Other Benefits → str
Commission PER → str
Commission Type → str
Hours Per → str
Hours Minimum → float64
Hours Maximum → float64
Work Hours → str
Work Hours From Time → str
Work Hours To Time → str

In [73]:
useful_columns = [
    "WIC Job Location Snapshot ID",
    "Job Title",
    "Original Job Title",
    "First Posting Date",
    "Vacancy Count",
    "Province/Territory",
    "City",
    "Economic  Region",
    "Employment Type",
    "Employment Term",
    "Education LOS",
    "Experience Level",
    "Salary Condition Detail",
    "Salary Per",
    "Salary Minimum",
    "Salary Maximum"
]


jobs_clean = jobs_clean[useful_columns].copy()

jobs_clean.shape

jobs_clean.head()

jobs_clean.isnull().sum()

jobs_clean.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 946 to 50505
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   WIC Job Location Snapshot ID  47 non-null     int64
 1   Job Title                     47 non-null     str
 2   Original Job Title            37 non-null     str
 3   First Posting Date            47 non-null     str
 4   Vacancy Count                 47 non-null     int64
 5   Province/Territory            47 non-null     str
 6   City                          47 non-null     str
 7   Economic  Region              47 non-null     str
 8   Employment Type               45 non-null     str
 9   Employment Term               43 non-null     str
 10  Education LOS                 6 non-null      str
 11  Experience Level              6 non-null      str
 12  Salary Condition Detail       47 non-null     str
 13  Salary Per                    47 non-null     str
 14  Salary Minimum                47 non-null     float64
 15  Salary Maximum                47 non-null     float64
dtypes: float64(2), int64(2), str(12)
memory usage: 13.3 KB

In [74]:
jobs_clean["First Posting Date"] = pd.to_datetime(
    jobs_clean["First Posting Date"],
    format="%Y/%m/%d"
)

jobs_clean.info()

jobs_clean[
    ["Job Title", "Salary Per", "Salary Minimum", "Salary Maximum"]
].head(10)

jobs_clean["Salary Per"].value_counts()

jobs_clean["Province/Territory"].value_counts()

<class 'pandas.DataFrame'>
Index: 47 entries, 946 to 50505
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   WIC Job Location Snapshot ID  47 non-null     int64
 1   Job Title                     47 non-null     str
 2   Original Job Title            37 non-null     str
 3   First Posting Date            47 non-null     datetime64[us]
 4   Vacancy Count                 47 non-null     int64
 5   Province/Territory            47 non-null     str
 6   City                          47 non-null     str
 7   Economic  Region              47 non-null     str
 8   Employment Type               45 non-null     str
 9   Employment Term               43 non-null     str
 10  Education LOS                 6 non-null      str
 11  Experience Level              6 non-null      str
 12  Salary Condition Detail       47 non-null     str
 13  Salary Per                    47 non-null     str
 14  Salary Minimum                47 non-null     float64
 15  Salary Maximum                47 non-null     float64
dtypes: datetime64[us](1), float64(2), int64(2), str(11)
memory usage: 12.9 KB

Province/Territory
Ontario             31
Québec               6
British Columbia     5
New Brunswick        2
Yukon                1
Nova Scotia          1
Alberta              1
Name: count, dtype: int64

In [75]:
print(jobs_clean["Salary Per"].value_counts())

print(
    jobs_clean[
        ["Salary Per", "Salary Minimum", "Salary Maximum"]
    ].to_string(index=False)
)

Salary Per
Hour         40
Year          5
Bi-weekly     2
Name: count, dtype: int64
Salary Per  Salary Minimum  Salary Maximum
      Year        73798.00        73798.00
      Hour           30.00           69.74
      Hour           20.34           26.00
      Hour           36.02           36.02
      Year        90000.00       120000.00
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           48.10           48.10
      Hour           43.00           43.00
      Hour           30.00           69.74
      Hour           30.00           69.74
      Year        55000.00        55000.00
      Hour           54.87           54.87
      Hour           42.00           45.00
 Bi-weekly         3410.48         4005.58
      Hour           20.00           20.00
      Hour           25.00           61.03
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           48.01           48.01
      Year        80000.00       100000.00
      Hour           44.50           44.50
 Bi-weekly         3577.88         3577.88
      Hour           41.50           41.50
      Hour           30.00           69.74
      Hour           25.00           61.03
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           25.00           61.03
      Hour           25.00           61.03
      Hour           25.00           61.03
      Hour           30.00           69.74
      Hour           26.00           78.00
      Hour           30.00           69.74
      Year        94193.00        94193.00
      Hour           36.02           36.02
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           30.00           69.74
      Hour           25.00           61.03
      Hour           25.00           61.03

In [76]:
def load_job_data(file_path):
    return pd.read_csv(
        file_path,
        sep="\t",
        encoding="utf-16"
    )

march_df = load_job_data(
    "../data/raw/March 2026 Data Set/job-bank-open-data-all-job-postings-en-mar2026.csv"
)
march_df.shape

may_df = load_job_data(
    "../data/raw/May 2026 Data Set/job-bank-open-data-all-job-postings-en-may2026 (1).csv"
)
may_df.shape

june_df = load_job_data(
    "../data/raw/June 2026 Data Set/job-bank-open-data-all-job-postings-en-june2026 (1).csv"
)
june_df.shape

july_df = load_job_data(
    "../data/raw/July 2026 Data Set/job-bank-open-data-all-job-postings-en-july2026 (1).csv"
)
july_df.shape

C:\Users\diwak\AppData\Local\Temp\ipykernel_21084\2688777336.py:2: DtypeWarning: Columns (0: Commission PER, 1: Commission Type) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(

(51999, 65)

In [77]:
def filter_data_jobs(df):
    keywords = (
        "data analyst|"
        "data scientist|"
        "business intelligence|"
        "bi analyst|"
        "analytics analyst|"
        "data analytics|"
        "data quality analyst|"
        "reporting analyst"
    )

    filtered = df[
        df["Job Title"].str.contains(
            keywords,
            case=False,
            na=False
        )
    ].copy()

    filtered = filtered[
        filtered["Job Title"].str.lower() != "data analytics manager"
    ].copy()

    return filtered

march_jobs = filter_data_jobs(march_df)
march_jobs.shape

april_jobs = filter_data_jobs(df)
april_jobs.shape

may_jobs = filter_data_jobs(may_df)
may_jobs.shape

june_jobs = filter_data_jobs(june_df)
june_jobs.shape

july_jobs = filter_data_jobs(july_df)
july_jobs.shape

(37, 65)

In [78]:
all_jobs = pd.concat(
    [
        march_jobs,
        april_jobs,
        may_jobs,
        june_jobs,
        july_jobs
    ],
    ignore_index=True
)
all_jobs.shape

all_jobs["First Posting Date"] = pd.to_datetime(
    all_jobs["First Posting Date"],
    format="%Y/%m/%d"
)

all_jobs["Month"] = all_jobs["First Posting Date"].dt.to_period("M")
all_jobs["Month"].value_counts().sort_index()

all_jobs["Job Title"].value_counts()

all_jobs["Province/Territory"].value_counts()

all_jobs["WIC Job Location Snapshot ID"].duplicated().sum()

all_jobs["WIC Job Location Snapshot ID"].nunique()

final_jobs = all_jobs.copy()

final_jobs.shape

final_jobs = final_jobs.reset_index(drop=True)
final_jobs.head()

final_jobs.columns = (
    final_jobs.columns
    .str.strip()
    .str.replace(r"\s+", "_", regex=True)
)
final_jobs.columns.tolist()

final_jobs.columns = (
    final_jobs.columns
    .str.replace("/", "_", regex=False)
)
final_jobs.columns.tolist()

['WIC_Job_Location_Snapshot_ID',
 'Job_Title',
 'Original_Job_Title',
 'NOC_2016_Code',
 'NOC_2016_Code_Name',
 'NOC21_Code',
 'NOC21_Code_Name',
 'External_Indicator',
 'First_Posting_Date',
 'Vacancy_Count',
 'Official_Language',
 'Education_LOS',
 'Experience_Level',
 'Government_Type',
 'Placement_Agency',
 'NAICS',
 'Province_Territory',
 'City',
 'Work_Location_Postal_Code',
 'Economic_Region',
 'Various_Location',
 'Employment_Type',
 'Employment_Term',
 'Employment_Term_Start_Date',
 'Employment_Term_End_Date',
 'Employment_Term_Oncall',
 'Employment_Term_Overtime',
 'Employment_Term_Day',
 'Employment_Term_Evening',
 'Employment_Term_Shift',
 'Employment_Term_Weekend',
 'Employment_Term_Night',
 'Employment_Term_Telework',
 'Employment_Term_Early',
 'Employment_Term_Flex',
 'Employment_Term_Morning',
 'Employment_Term_TBD',
 'Salary_Condition_Detail',
 'Salary_Per',
 'Salary_Minimum',
 'Salary_Maximum',
 'Salary_Condition_Collective',
 'Salary_Condition_Bonus',
 'Salary_Condition_Disability',
 'Salary_Condition_Gratuity',
 'Salary_Condition_Medical',
 'Salary_Condition_Mileage',
 'Salary_Condition_Piecework',
 'Salary_Condition_Commission',
 'Salary_Condition_RESP',
 'Salary_Condition_Dental',
 'Salary_Condition_Group_Insurance',
 'Salary_Condition_Life_Insurance',
 'Salary_Condition_Pension',
 'Salary_Condition_RRSP',
 'Condition_Vision_Care',
 'Salary_Condition_Other_Benefits',
 'Commission_PER',
 'Commission_Type',
 'Hours_Per',
 'Hours_Minimum',
 'Hours_Maximum',
 'Work_Hours',
 'Work_Hours_From_Time',
 'Work_Hours_To_Time',
 'Month']

In [79]:
missing_values = final_jobs.isnull().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

missing_percent = (
    final_jobs.isnull().mean() * 100
).round(1)

missing_percent[missing_percent > 0].sort_values(ascending=False)

Commission_Type                     100.0
Commission_PER                      100.0
Work_Hours_To_Time                   99.6
Work_Hours_From_Time                 99.6
Employment_Term_End_Date             99.1
Employment_Term_Start_Date           94.0
Government_Type                      83.7
Placement_Agency                     82.4
Employment_Term_Day                  82.4
Employment_Term_Overtime             82.4
Experience_Level                     82.4
Employment_Term_TBD                  82.4
Employment_Term_Night                82.4
Employment_Term_Weekend              82.4
Employment_Term_Shift                82.4
Employment_Term_Evening              82.4
NAICS                                82.4
Employment_Term_Oncall               82.4
Salary_Condition_Collective          82.4
Education_LOS                        82.4
Salary_Condition_Piecework           82.4
Salary_Condition_Mileage             82.4
Salary_Condition_Medical             82.4
Salary_Condition_Gratuity            82.4
Salary_Condition_Commission          82.4
Salary_Condition_RESP                82.4
Salary_Condition_Dental              82.4
Salary_Condition_Group_Insurance     82.4
Condition_Vision_Care                82.4
Salary_Condition_RRSP                82.4
Salary_Condition_Bonus               82.4
Salary_Condition_Disability          82.4
Employment_Term_Telework             82.4
Employment_Term_Early                82.4
Employment_Term_Flex                 82.4
Employment_Term_Morning              82.4
Hours_Per                            82.4
Salary_Condition_Other_Benefits      82.4
Salary_Condition_Pension             82.4
Salary_Condition_Life_Insurance      82.4
Hours_Maximum                        80.3
Hours_Minimum                        80.3
Work_Location_Postal_Code            79.8
Original_Job_Title                   30.0
Employment_Term                      21.5
NOC_2016_Code_Name                    4.3
NOC21_Code                            4.3
NOC_2016_Code                         4.3
NOC21_Code_Name                       4.3
Employment_Type                       3.9
Economic_Region                       2.6
City                                  2.6
dtype: float64

In [80]:
final_columns = [
    "WIC_Job_Location_Snapshot_ID",
    "Job_Title",
    "Original_Job_Title",
    "NOC21_Code",
    "NOC21_Code_Name",
    "First_Posting_Date",
    "Month",
    "Vacancy_Count",
    "Province_Territory",
    "City",
    "Economic_Region",
    "Employment_Type",
    "Employment_Term",
    "Education_LOS",
    "Experience_Level",
    "Salary_Condition_Detail",
    "Salary_Per",
    "Salary_Minimum",
    "Salary_Maximum"
]
final_jobs = final_jobs[final_columns].copy()
final_jobs.shape

final_jobs.isnull().sum().sort_values(ascending=False)

final_columns = [
    "WIC_Job_Location_Snapshot_ID",
    "Job_Title",
    "Original_Job_Title",
    "NOC21_Code",
    "NOC21_Code_Name",
    "First_Posting_Date",
    "Month",
    "Vacancy_Count",
    "Province_Territory",
    "City",
    "Economic_Region",
    "Employment_Type",
    "Employment_Term",
    "Education_LOS",
    "Experience_Level",
    "Salary_Condition_Detail",
    "Salary_Per",
    "Salary_Minimum",
    "Salary_Maximum"
]

final_jobs = final_jobs[final_columns].copy()
final_jobs.shape
final_jobs.isnull().sum().sort_values(ascending=False)

categorical_columns = [
    "Original_Job_Title",
    "Employment_Term",
    "Education_LOS",
    "Experience_Level",
    "NOC21_Code_Name",
    "Employment_Type",
    "City",
    "Economic_Region"
]

for column in categorical_columns:
    final_jobs[column] = final_jobs[column].fillna("Not specified")

final_jobs.isnull().sum().sort_values(ascending=False)

final_jobs.shape

(233, 19)

In [81]:
def annual_salary(value, salary_per):
    if salary_per == "Year":
        return value
    
    elif salary_per == "Hour":
        return value * 40 * 52
    
    elif salary_per == "Bi-weekly":
        return value * 26
    
    else:
        return None

final_jobs["Estimated_Annual_Min"] = final_jobs.apply(
    lambda row: annual_salary(
        row["Salary_Minimum"],
        row["Salary_Per"]
    ),
    axis=1
)

final_jobs["Estimated_Annual_Max"] = final_jobs.apply(
    lambda row: annual_salary(
        row["Salary_Maximum"],
        row["Salary_Per"]
    ),
    axis=1
)

final_jobs["Estimated_Annual_Mid"] = (
    final_jobs["Estimated_Annual_Min"] +
    final_jobs["Estimated_Annual_Max"]
) / 2

final_jobs[
    [
        "Job_Title",
        "Salary_Per",
        "Salary_Minimum",
        "Salary_Maximum",
        "Estimated_Annual_Min",
        "Estimated_Annual_Max",
        "Estimated_Annual_Mid"
    ]
].head(15)

,Job_Title,Salary_Per,Salary_Minimum,Salary_Maximum,Estimated_Annual_Min,Estimated_Annual_Max,Estimated_Annual_Mid
0,data scientist,Hour,30.0,69.74,62400.0,145059.2,103729.6
1,data analyst - informatics and systems,Hour,45.0,45.00,93600.0,93600.0,93600.0
2,data analyst - informatics and systems,Hour,25.0,61.03,52000.0,126942.4,89471.2
3,data analyst - informatics and systems,Hour,24.0,58.00,49920.0,120640.0,85280.0
4,business data analyst,Bi-weekly,3850.0,3850.00,100100.0,100100.0,100100.0
5,data analyst - informatics and systems,Year,66924.0,93470.00,66924.0,93470.0,80197.0
6,data scientist,Hour,30.0,69.74,62400.0,145059.2,103729.6
7,business data analyst,Hour,48.1,48.10,100048.0,100048.0,100048.0
8,data scientist,Hour,30.0,69.74,62400.0,145059.2,103729.6
9,big data analyst,Year,85000.0,100000.00,85000.0,100000.0,92500.0
10,data analyst - informatics and systems,Hour,25.0,61.03,52000.0,126942.4,89471.2
11,data scientist,Hour,30.0,69.74,62400.0,145059.2,103729.6
12,data analyst - informatics and systems,Hour,25.0,61.03,52000.0,126942.4,89471.2
13,data analyst - informatics and systems,Hour,25.0,61.03,52000.0,126942.4,89471.2
14,data analyst - informatics and systems,Hour,25.0,61.03,52000.0,126942.4,89471.2

In [82]:
all_jobs.shape

(233, 66)

In [83]:
final_jobs.shape

(233, 22)

In [84]:
final_jobs[
    final_jobs["Salary_Maximum"] > 1000
][
    [
        "Job_Title",
        "Salary_Per",
        "Salary_Minimum",
        "Salary_Maximum",
        "Salary_Condition_Detail",
        "Estimated_Annual_Min",
        "Estimated_Annual_Max"
    ]
]

,Job_Title,Salary_Per,Salary_Minimum,Salary_Maximum,Salary_Condition_Detail,Estimated_Annual_Min,Estimated_Annual_Max
4,business data analyst,Bi-weekly,3850.00,3850.00,"$3,850.00 biweekly",100100.00,100100.00
5,data analyst - informatics and systems,Year,66924.00,93470.00,"$66,924.00 to $93,470.00 annually",66924.00,93470.00
9,big data analyst,Year,85000.00,100000.00,"$85,000.00 to $100,000.00 annually",85000.00,100000.00
17,data scientist,Year,53094.34,116898.51,"$53,094.34 to $116,898.51 annually",53094.34,116898.51
24,data analyst - informatics and systems,Year,66924.00,93470.00,"$66,924.00 to $93,470.00 annually",66924.00,93470.00
...,...,...,...,...,...,...,...
221,data analytics specialist,Year,63408.00,70453.00,"$63,408.00 to $70,453.00 annually",63408.00,70453.00
223,data analytics specialist,Year,79000.00,82000.00,"$79,000.00 to $82,000.00 annually (to be negot...",79000.00,82000.00
225,business intelligence specialist,Year,75000.00,75000.00,"$75,000.00 annually",75000.00,75000.00
228,big data analyst,Year,60000.00,70000.00,"$60,000.00 to $70,000.00 annually",60000.00,70000.00
231,"Data Analyst, Senior Data Analyst and Data Adv...",Year,83862.00,83862.00,"$83,862.00 annually",83862.00,83862.00

In [85]:
suspicious_hourly = final_jobs[
    (final_jobs["Salary_Per"] == "Hour") &
    (final_jobs["Salary_Maximum"] > 200)
].copy()

suspicious_hourly[
    [
        "Job_Title",
        "Salary_Per",
        "Salary_Minimum",
        "Salary_Maximum",
        "Salary_Condition_Detail",
        "Estimated_Annual_Min",
        "Estimated_Annual_Max"
    ]
]

,Job_Title,Salary_Per,Salary_Minimum,Salary_Maximum,Salary_Condition_Detail,Estimated_Annual_Min,Estimated_Annual_Max
31,data analyst - informatics and systems,Hour,34.9,5308.29,"$34.90 ($5,308.29) - $44.36 ($6,747.16)",72592.0,11041243.2
179,data scientist,Hour,100000.0,115000.00,"$100,000.00 to $115,000.00 hourly",208000000.0,239200000.0

In [86]:
final_jobs[
    final_jobs["Salary_Per"] == "Hour"
][
    "Salary_Maximum"
].describe()

count       149.000000
mean        866.062886
std        9423.218183
min          20.000000
25%          48.100000
50%          61.030000
75%          69.740000
max      115000.000000
Name: Salary_Maximum, dtype: float64

In [87]:
final_jobs["Salary_Valid"] = True

final_jobs.loc[
    (final_jobs["Salary_Per"] == "Hour") &
    (final_jobs["Salary_Maximum"] > 200),
    "Salary_Valid"
] = False

In [88]:
final_jobs["Salary_Valid"].value_counts()

Salary_Valid
True     231
False      2
Name: count, dtype: int64

In [89]:
salary_jobs = final_jobs[
    final_jobs["Salary_Valid"]
].copy()

salary_jobs.shape

(231, 23)

In [90]:
salary_jobs[
    [
        "Estimated_Annual_Min",
        "Estimated_Annual_Max",
        "Estimated_Annual_Mid"
    ]
].describe()

       Estimated_Annual_Min  Estimated_Annual_Max  Estimated_Annual_Mid
count            227.000000            227.000000            227.000000
mean           72201.581938         112144.350529          92172.966233
std            22055.350096          29853.491380          18619.515194
min            37315.200000          41600.000000          41600.000000
25%            60139.500000          89248.000000          82212.000000
50%            62400.000000         116898.510000          92500.000000
75%            85427.000000         145059.200000         103729.600000
max           178396.920000         178396.920000         178396.920000

In [91]:
salary_jobs[
    salary_jobs["Estimated_Annual_Max"] == salary_jobs["Estimated_Annual_Max"].max()
][
    [
        "Job_Title",
        "Province_Territory",
        "City",
        "Salary_Per",
        "Salary_Minimum",
        "Salary_Maximum",
        "Salary_Condition_Detail",
        "Estimated_Annual_Min",
        "Estimated_Annual_Max"
    ]
]

,Job_Title,Province_Territory,City,Salary_Per,Salary_Minimum,Salary_Maximum,Salary_Condition_Detail,Estimated_Annual_Min,Estimated_Annual_Max
28,data scientist,Alberta,Calgary,Year,178396.92,178396.92,"$178,396.92 annually",178396.92,178396.92

In [92]:
import os

os.makedirs("../data/processed", exist_ok=True)

salary_jobs.to_csv(
    "../data/processed/canada_data_jobs_clean.csv",
    index=False
)

In [93]:
pd.read_csv(
    "../data/processed/canada_data_jobs_clean.csv"
).shape

(231, 23)

In [94]:
df = pd.read_csv(
    "../data/raw/April 2026 Data Set/job-bank-open-data-all-job-postings-en-apr2026.csv",
    sep="\t",
    encoding="utf-16"
)

[
    column
    for column in df.columns
    if any(
        word in column.lower()
        for word in ["description", "skill", "requirement", "duty", "qualification"]
    )
]

for i, column in enumerate(df.columns, start=1):
    print(i, ":", column)


for start in range(0, len(df.columns), 10):
    print(f"\n--- Columns {start + 1} to {min(start + 10, len(df.columns))} ---")
    
    for i, column in enumerate(
        df.columns[start:start + 10],
        start=start + 1
    ):
        print(i, ":", column)

1 : WIC Job Location Snapshot ID
2 : Job Title
3 : Original Job Title
4 : NOC 2016 Code
5 : NOC 2016 Code Name
6 : NOC21 Code
7 : NOC21 Code Name
8 : External Indicator
9 : First Posting Date
10 : Vacancy Count
11 : Official Language
12 : Education LOS
13 : Experience Level
14 : Government Type
15 : Placement Agency
16 : NAICS
17 : Province/Territory
18 : City
19 : Work Location Postal Code
20 : Economic  Region
21 : Various Location
22 : Employment Type
23 : Employment Term
24 : Employment Term Start Date
25 : Employment Term End Date
26 : Employment Term Oncall
27 : Employment Term Overtime
28 : Employment Term Day
29 : Employment Term Evening
30 : Employment Term Shift
31 : Employment Term Weekend
32 : Employment Term Night
33 : Employment Term Telework
34 : Employment Term Early
35 : Employment Term Flex
36 : Employment Term Morning
37 : Employment Term TBD
38 : Salary Condition Detail
39 : Salary Per
40 : Salary Minimum
41 : Salary Maximum
42 : Salary Condition Collective
43 : Salary Condition Bonus
44 : Salary Condition Disability
45 : Salary Condition Gratuity
46 : Salary Condition Medical
47 : Salary Condition Mileage
48 : Salary Condition Piecework
49 : Salary Condition Commission
50 : Salary Condition RESP
51 : Salary Condition Dental
52 : Salary Condition Group Insurance
53 : Salary Condition Life Insurance
54 : Salary Condition Pension
55 : Salary Condition RRSP
56 : Condition Vision Care
57 : Salary Condition Other Benefits
58 : Commission PER
59 : Commission Type
60 : Hours Per
61 : Hours Minimum
62 : Hours Maximum
63 : Work Hours
64 : Work Hours From Time
65 : Work Hours To Time

--- Columns 1 to 10 ---
1 : WIC Job Location Snapshot ID
2 : Job Title
3 : Original Job Title
4 : NOC 2016 Code
5 : NOC 2016 Code Name
6 : NOC21 Code
7 : NOC21 Code Name
8 : External Indicator
9 : First Posting Date
10 : Vacancy Count

--- Columns 11 to 20 ---
11 : Official Language
12 : Education LOS
13 : Experience Level
14 : Government Type
15 : Placement Agency
16 : NAICS
17 : Province/Territory
18 : City
19 : Work Location Postal Code
20 : Economic  Region

--- Columns 21 to 30 ---
21 : Various Location
22 : Employment Type
23 : Employment Term
24 : Employment Term Start Date
25 : Employment Term End Date
26 : Employment Term Oncall
27 : Employment Term Overtime
28 : Employment Term Day
29 : Employment Term Evening
30 : Employment Term Shift

--- Columns 31 to 40 ---
31 : Employment Term Weekend
32 : Employment Term Night
33 : Employment Term Telework
34 : Employment Term Early
35 : Employment Term Flex
36 : Employment Term Morning
37 : Employment Term TBD
38 : Salary Condition Detail
39 : Salary Per
40 : Salary Minimum

--- Columns 41 to 50 ---
41 : Salary Maximum
42 : Salary Condition Collective
43 : Salary Condition Bonus
44 : Salary Condition Disability
45 : Salary Condition Gratuity
46 : Salary Condition Medical
47 : Salary Condition Mileage
48 : Salary Condition Piecework
49 : Salary Condition Commission
50 : Salary Condition RESP

--- Columns 51 to 60 ---
51 : Salary Condition Dental
52 : Salary Condition Group Insurance
53 : Salary Condition Life Insurance
54 : Salary Condition Pension
55 : Salary Condition RRSP
56 : Condition Vision Care
57 : Salary Condition Other Benefits
58 : Commission PER
59 : Commission Type
60 : Hours Per

--- Columns 61 to 65 ---
61 : Hours Minimum
62 : Hours Maximum
63 : Work Hours
64 : Work Hours From Time
65 : Work Hours To Time

In [95]:
columns_df = pd.DataFrame({
    "Column Number": range(1, len(df.columns) + 1),
    "Column Name": df.columns
})

columns_df

    Column Number                   Column Name
0               1  WIC Job Location Snapshot ID
1               2                     Job Title
2               3            Original Job Title
3               4                 NOC 2016 Code
4               5            NOC 2016 Code Name
..            ...                           ...
60             61                 Hours Minimum
61             62                 Hours Maximum
62             63                    Work Hours
63             64          Work Hours From Time
64             65            Work Hours To Time

[65 rows x 2 columns]

In [96]:
for i in range(25, 61):
    print(f"{i + 1}: {df.columns[i]}")

26: Employment Term Oncall
27: Employment Term Overtime
28: Employment Term Day
29: Employment Term Evening
30: Employment Term Shift
31: Employment Term Weekend
32: Employment Term Night
33: Employment Term Telework
34: Employment Term Early
35: Employment Term Flex
36: Employment Term Morning
37: Employment Term TBD
38: Salary Condition Detail
39: Salary Per
40: Salary Minimum
41: Salary Maximum
42: Salary Condition Collective
43: Salary Condition Bonus
44: Salary Condition Disability
45: Salary Condition Gratuity
46: Salary Condition Medical
47: Salary Condition Mileage
48: Salary Condition Piecework
49: Salary Condition Commission
50: Salary Condition RESP
51: Salary Condition Dental
52: Salary Condition Group Insurance
53: Salary Condition Life Insurance
54: Salary Condition Pension
55: Salary Condition RRSP
56: Condition Vision Care
57: Salary Condition Other Benefits
58: Commission PER
59: Commission Type
60: Hours Per
61: Hours Minimum

In [97]:
df = pd.read_csv(
    "../data/raw/April 2026 Data Set/job-bank-open-data-all-job-postings-en-apr2026.csv",
    sep="\t",
    encoding="utf-16"
)
[
    column
    for column in df.columns
    if any(
        word in column.lower()
        for word in ["description", "skill", "requirement", "duty", "qualification"]
    )
]
for i, column in enumerate(df.columns):
    print(f"{i + 1}: {column}")

1: WIC Job Location Snapshot ID
2: Job Title
3: Original Job Title
4: NOC 2016 Code
5: NOC 2016 Code Name
6: NOC21 Code
7: NOC21 Code Name
8: External Indicator
9: First Posting Date
10: Vacancy Count
11: Official Language
12: Education LOS
13: Experience Level
14: Government Type
15: Placement Agency
16: NAICS
17: Province/Territory
18: City
19: Work Location Postal Code
20: Economic  Region
21: Various Location
22: Employment Type
23: Employment Term
24: Employment Term Start Date
25: Employment Term End Date
26: Employment Term Oncall
27: Employment Term Overtime
28: Employment Term Day
29: Employment Term Evening
30: Employment Term Shift
31: Employment Term Weekend
32: Employment Term Night
33: Employment Term Telework
34: Employment Term Early
35: Employment Term Flex
36: Employment Term Morning
37: Employment Term TBD
38: Salary Condition Detail
39: Salary Per
40: Salary Minimum
41: Salary Maximum
42: Salary Condition Collective
43: Salary Condition Bonus
44: Salary Condition Disability
45: Salary Condition Gratuity
46: Salary Condition Medical
47: Salary Condition Mileage
48: Salary Condition Piecework
49: Salary Condition Commission
50: Salary Condition RESP
51: Salary Condition Dental
52: Salary Condition Group Insurance
53: Salary Condition Life Insurance
54: Salary Condition Pension
55: Salary Condition RRSP
56: Condition Vision Care
57: Salary Condition Other Benefits
58: Commission PER
59: Commission Type
60: Hours Per
61: Hours Minimum
62: Hours Maximum
63: Work Hours
64: Work Hours From Time
65: Work Hours To Time

In [98]:
import pandas as pd
import csv

file_path = "../data/raw/OaSIS Skills/skills_oasis_2025_v1.1.csv"

with open(file_path, "r", encoding="utf-8-sig") as file:
    sample = file.read(5000)


detected_separator = csv.Sniffer().sniff(
    sample,
    delimiters=",;\t|"
).delimiter

print("Detected separator:", repr(detected_separator))


oasis_skills = pd.read_csv(
    file_path,
    sep=detected_separator,
    encoding="utf-8-sig"
)

print("\nDataset shape:")
print(oasis_skills.shape)

print("\nColumn names:")
print(oasis_skills.columns.tolist())

print("\nFirst 5 rows:")
display(oasis_skills.head())


print("Job Bank NOC21 codes:")
print(
    final_jobs["NOC21_Code"]
    .dropna()
    .astype(int)
    .astype(str)
    .unique()[:20]
)

print("\nOaSIS codes:")
print(
    oasis_skills["Code OaSIS"]
    .dropna()
    .astype(str)
    .head(20)
    .tolist()
)


oasis_skills["OaSIS_Code_String"] = (
    oasis_skills["Code OaSIS"]
    .astype(str)
)


oasis_skills["NOC21_Code_Clean"] = (
    oasis_skills["OaSIS_Code_String"]
    .str.split(".")
    .str[0]
    .str.zfill(5)
)


final_jobs["NOC21_Code_Clean"] = (
    final_jobs["NOC21_Code"]
    .astype("Int64")
    .astype(str)
    .str.zfill(5)
)



print("Job Bank NOC codes:")

print(
    final_jobs["NOC21_Code_Clean"]
    .dropna()
    .unique()
)


matching_oasis = oasis_skills[
    oasis_skills["NOC21_Code_Clean"].isin(
        final_jobs["NOC21_Code_Clean"].dropna().unique()
    )
].copy()


print("\nNumber of matching OaSIS profiles:")
print(len(matching_oasis))


print("\nMatching occupations:")

display(
    matching_oasis[
        [
            "Code OaSIS",
            "NOC21_Code_Clean",
            "OaSIS 2021 Labels"
        ]
    ]
)


selected_skills = [
    "Digital Literacy",
    "Numeracy",
    "Problem Solving",
    "Systems Analysis",
    "Critical Thinking",
    "Decision Making",
    "Reading Comprehension",
    "Writing",
    "Troubleshooting",
    "Time Management"
]



relevant_oasis = oasis_skills[
    oasis_skills["NOC21_Code_Clean"].isin(
        final_jobs["NOC21_Code_Clean"].dropna().unique()
    )
].copy()



noc_skill_profiles = (
    relevant_oasis
    .groupby("NOC21_Code_Clean")[selected_skills]
    .mean()
    .reset_index()
)


print("Number of NOC skill profiles:")
print(noc_skill_profiles.shape)


print("\nSkill profiles:")

display(noc_skill_profiles)



jobs_with_skills = final_jobs.merge(
    noc_skill_profiles,
    on="NOC21_Code_Clean",
    how="left"
)


print("\nOriginal job dataset:")
print(final_jobs.shape)

print("\nDataset after adding skills:")
print(jobs_with_skills.shape)



print("\nNumber of rows before merge:")
print(len(final_jobs))

print("\nNumber of rows after merge:")
print(len(jobs_with_skills))



print("\nJobs with OaSIS skill information:")

print(
    jobs_with_skills["Digital Literacy"]
    .notna()
    .sum()
)


# --------------------------------------------------
# 6. Calculate average skill ratings across
#    the occupations represented by our postings
# --------------------------------------------------

average_skills = (
    jobs_with_skills[selected_skills]
    .mean()
    .sort_values(ascending=False)
)


print("\nAverage occupational skill ratings:")

display(average_skills)

Detected separator: ';'

Dataset shape:
(900, 35)

Column names:
['Code OaSIS', 'OaSIS 2021 Labels', 'Oral Communication: Active Listening', 'Digital Literacy', 'Numeracy', 'Oral Communication: Oral Comprehension', 'Oral Communication: Oral Expression', 'Reading Comprehension', 'Writing', 'Decision Making', 'Evaluation', 'Learning and Teaching Strategies', 'Problem Solving', 'Systems Analysis', 'Critical Thinking', 'Digital Systems Production', 'Equipment and Tool Selection', 'Operation and Control', 'Operation Monitoring of Machinery and Equipment', 'Preventative Maintenance', 'Product Design', 'Quality Control Testing', 'Repairing', 'Setting Up', 'Troubleshooting', 'Management of Financial Resources', 'Management of Material Resources', 'Management of Personnel Resources', 'Monitoring', 'Time Management', 'Coordinating', 'Instructing', 'Negotiating', 'Persuading', 'Social Perceptiveness']

First 5 rows:

,Code OaSIS,OaSIS 2021 Labels,Oral Communication: Active Listening,Digital Literacy,Numeracy,Oral Communication: Oral Comprehension,Oral Communication: Oral Expression,Reading Comprehension,Writing,Decision Making,...,Management of Financial Resources,Management of Material Resources,Management of Personnel Resources,Monitoring,Time Management,Coordinating,Instructing,Negotiating,Persuading,Social Perceptiveness
0,10.0,Legislators,4,3,3,5,5,4,4,5,...,5,5,5,5,5,5,3,5,5,5
1,11.0,Senior government managers and officials,4,4,4,5,5,5,5,5,...,5,5,5,5,5,5,4,5,5,4
2,12.0,"Senior managers - financial, communications an...",4,4,4,5,5,5,5,5,...,5,5,5,5,5,5,4,5,5,4
3,13.0,"Senior managers - health, education, social an...",4,4,4,5,5,5,5,5,...,5,5,5,5,5,5,4,5,5,5
4,14.0,"Senior managers - trade, broadcasting and othe...",4,4,4,5,5,5,5,5,...,5,5,5,5,5,5,4,5,5,4

Job Bank NOC21 codes:
<ArrowStringArray>
['21211', '21223', '21221', '41402']
Length: 4, dtype: str

OaSIS codes:
['10.0', '11.0', '12.0', '13.0', '14.0', '15.0', '10010.0', '10011.0', '10012.0', '10019.0', '10020.01', '10020.02', '10020.03', '10020.04', '10021.01', '10021.02', '10022.01', '10022.02', '10022.03', '10022.04']
Job Bank NOC codes:
<ArrowStringArray>
['21211', '21223', '21221', '41402']
Length: 4, dtype: str

Number of matching OaSIS profiles:
5

Matching occupations:

,Code OaSIS,NOC21_Code_Clean,OaSIS 2021 Labels
126,21211.00,21211,Data scientists
128,21221.00,21221,Business system specialists
130,21223.01,21223,Database analysts
131,21223.02,21223,Data administrators
354,41402.00,41402,Business development officers and market resea...

Number of NOC skill profiles:
(4, 11)

Skill profiles:

,NOC21_Code_Clean,Digital Literacy,Numeracy,Problem Solving,Systems Analysis,Critical Thinking,Decision Making,Reading Comprehension,Writing,Troubleshooting,Time Management
0,21211,5.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,3.0
1,21221,5.0,4.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0
2,21223,4.0,3.5,4.5,4.0,4.0,4.0,4.0,3.5,3.0,3.0
3,41402,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,0.0,3.0

Original job dataset:
(233, 24)

Dataset after adding skills:
(233, 34)

Number of rows before merge:
233

Number of rows after merge:
233

Jobs with OaSIS skill information:
223

Average occupational skill ratings:

Problem Solving          4.834081
Digital Literacy         4.672646
Critical Thinking        4.672646
Systems Analysis         4.672646
Numeracy                 4.421525
Decision Making          4.000000
Reading Comprehension    4.000000
Writing                  3.838565
Troubleshooting          3.659193
Time Management          3.089686
dtype: float64

In [99]:
# --------------------------------------------------
# STEP 15: INVESTIGATE JOBS WITHOUT OaSIS SKILLS
# --------------------------------------------------

unmatched_jobs = jobs_with_skills[
    jobs_with_skills["Digital Literacy"].isna()
].copy()

print("Number of unmatched jobs:")
print(len(unmatched_jobs))

print("\nNOC codes of unmatched jobs:")
print(
    unmatched_jobs["NOC21_Code"].value_counts(dropna=False)
)

print("\nUnmatched job details:")

display(
    unmatched_jobs[
        [
            "Job_Title",
            "Original_Job_Title",
            "NOC21_Code",
            "NOC21_Code_Name",
            "Province_Territory",
            "City"
        ]
    ]
)

Number of unmatched jobs:
10

NOC codes of unmatched jobs:
NOC21_Code
NaN    10
Name: count, dtype: int64

Unmatched job details:

,Job_Title,Original_Job_Title,NOC21_Code,NOC21_Code_Name,Province_Territory,City
57,"Senior Advisor/ Data Scientist, Advanced Analy...",Not specified,NaN,Not specified,Ontario,Ottawa
75,Strategic Business Planning and Reporting Analyst,Not specified,NaN,Not specified,Yukon,Whitehorse
157,Business Intelligence Developer,Not specified,NaN,Not specified,Ontario,Ottawa
162,"Information Technology (IT) Data Analyst, IT S...",Not specified,NaN,Not specified,Ontario,Sudbury
168,Senior Data Scientist - Financial Markets,Not specified,NaN,Not specified,Ontario,Ottawa
175,"Data Analyst, Regulatory Reporting",Not specified,NaN,Not specified,Ontario,Ottawa
181,"Business Intelligence Analyst, Operations",Not specified,NaN,Not specified,Ontario,Ottawa
207,"Business Analyst, Data Analytics (#25370)",Not specified,NaN,Not specified,Ontario,Ottawa
212,Geoscience Data Analyst,Not specified,NaN,Not specified,Ontario,Ottawa
231,"Data Analyst, Senior Data Analyst and Data Adv...",Not specified,NaN,Not specified,Ontario,Ottawa

In [100]:


import os

# Make sure processed folder exists
os.makedirs("../data/processed", exist_ok=True)



jobs_with_skills.to_csv(
    "../data/processed/jobs_with_skills.csv",
    index=False
)

print("Saved: jobs_with_skills.csv")



noc_skill_profiles.to_csv(
    "../data/processed/noc_skill_profiles.csv",
    index=False
)

print("Saved: noc_skill_profiles.csv")


skill_summary = (
    average_skills
    .reset_index()
)

skill_summary.columns = [
    "Skill",
    "Average_Rating"
]

skill_summary.to_csv(
    "../data/processed/skill_summary.csv",
    index=False
)

print("Saved: skill_summary.csv")



print("\nFiles currently in processed folder:")

for file in os.listdir("../data/processed"):
    print(file)


print("\nShapes:")

print(
    "Jobs with skills:",
    pd.read_csv(
        "../data/processed/jobs_with_skills.csv"
    ).shape
)

print(
    "NOC skill profiles:",
    pd.read_csv(
        "../data/processed/noc_skill_profiles.csv"
    ).shape
)

print(
    "Skill summary:",
    pd.read_csv(
        "../data/processed/skill_summary.csv"
    ).shape
)


print("\nSkill summary:")

display(
    pd.read_csv(
        "../data/processed/skill_summary.csv"
    )
)

Saved: jobs_with_skills.csv
Saved: noc_skill_profiles.csv
Saved: skill_summary.csv

Files currently in processed folder:
canada_data_jobs_clean.csv
direct_job_bank_postings.csv
final_unchecked_technology_jobs.csv
jobs_with_skills.csv
job_market.db
noc_skill_profiles.csv
remaining_technology_jobs.csv
skill_summary.csv
technology_collection.csv
technology_demand.csv
technology_mentions.csv
verified_technology_jobs.csv

Shapes:
Jobs with skills: (233, 34)
NOC skill profiles: (4, 11)
Skill summary: (10, 2)

Skill summary:

                   Skill  Average_Rating
0        Problem Solving        4.834081
1       Digital Literacy        4.672646
2      Critical Thinking        4.672646
3       Systems Analysis        4.672646
4               Numeracy        4.421525
5        Decision Making        4.000000
6  Reading Comprehension        4.000000
7                Writing        3.838565
8        Troubleshooting        3.659193
9        Time Management        3.089686

In [101]:


import pandas as pd
import glob
import os



job_files = glob.glob(
    "../data/raw/*/job-bank-open-data-all-job-postings-en-*.csv"
)

print("Monthly files found:", len(job_files))


direct_data = []

for file in job_files:

    temp = pd.read_csv(
        file,
        sep="\t",
        encoding="utf-16",
        usecols=[
            "WIC Job Location Snapshot ID",
            "Job Title",
            "Original Job Title",
            "External Indicator",
            "First Posting Date",
            "Province/Territory",
            "City",
            "NOC21 Code",
            "Salary Per",
            "Salary Minimum",
            "Salary Maximum",
            "Salary Condition Detail"
        ]
    )

    direct_data.append(temp)


raw_direct = pd.concat(
    direct_data,
    ignore_index=True
)



keywords = (
    "data analyst|"
    "data scientist|"
    "business intelligence|"
    "bi analyst|"
    "analytics analyst|"
    "data analytics|"
    "data quality analyst|"
    "reporting analyst"
)


direct_jobs = raw_direct[
    raw_direct["Job Title"].str.contains(
        keywords,
        case=False,
        na=False
    )
].copy()




direct_jobs = direct_jobs[
    direct_jobs["Job Title"].str.lower()
    != "data analytics manager"
].copy()


direct_jobs = direct_jobs[
    direct_jobs["External Indicator"] == 0
].copy()


direct_jobs["First Posting Date"] = pd.to_datetime(
    direct_jobs["First Posting Date"],
    format="%Y/%m/%d"
)




direct_jobs = direct_jobs.sort_values(
    "First Posting Date"
).reset_index(drop=True)



print("Direct Job Bank postings:")
print(direct_jobs.shape)


print("\nPostings by month:")

print(
    direct_jobs["First Posting Date"]
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)


print("\nPostings by title:")

print(
    direct_jobs["Job Title"]
    .value_counts()
)


print("\nMatching information:")

display(
    direct_jobs[
        [
            "WIC Job Location Snapshot ID",
            "Job Title",
            "Original Job Title",
            "First Posting Date",
            "Province/Territory",
            "City",
            "Salary Per",
            "Salary Minimum",
            "Salary Maximum"
        ]
    ]
)

Monthly files found: 5
Direct Job Bank postings:
(41, 12)

Postings by month:
First Posting Date
2026-03    11
2026-04     6
2026-05     6
2026-06    10
2026-07     8
Freq: M, Name: count, dtype: int64

Postings by title:
Job Title
data analyst - informatics and systems    13
data scientist                             9
business data analyst                      8
data analytics specialist                  6
data quality analyst                       2
business intelligence specialist           2
marketing data analyst                     1
Name: count, dtype: int64

Matching information:

,WIC Job Location Snapshot ID,Job Title,Original Job Title,First Posting Date,Province/Territory,City,Salary Per,Salary Minimum,Salary Maximum
0,15293390,marketing data analyst,NaN,2026-03-01,Ontario,Markham,Hour,48.00,48.00
1,15294248,data analyst - informatics and systems,NaN,2026-03-02,Ontario,Richmond Hill,Hour,45.00,45.00
2,15306899,data scientist,NaN,2026-03-06,Québec,NaN,Hour,46.15,46.15
3,15323256,data scientist,NaN,2026-03-12,Ontario,Mississauga,Year,98000.00,150000.00
4,15323309,data analyst - informatics and systems,NaN,2026-03-13,Ontario,Etobicoke,Hour,43.96,43.96
5,15323259,data analyst - informatics and systems,NaN,2026-03-13,Ontario,Mississauga,Hour,43.96,43.96
6,15341700,data scientist,NaN,2026-03-20,Ontario,NaN,Year,85000.00,95000.00
7,15342796,business data analyst,NaN,2026-03-20,Alberta,Edmonton,Hour,48.10,48.10
8,15342389,data analytics specialist,NaN,2026-03-20,Ontario,Cambridge,Hour,25.00,35.00
9,15355332,business data analyst,NaN,2026-03-25,Ontario,Nepean,Bi-weekly,3850.00,3850.00
10,15363720,data analytics specialist,NaN,2026-03-30,Ontario,Toronto,Year,80000.00,115000.00
11,15376895,data scientist,NaN,2026-04-03,New Brunswick,Shediac,Hour,42.00,45.00
12,15488194,data scientist,NaN,2026-04-22,British Columbia,Burnaby,Hour,48.10,48.10
13,15491326,business data analyst,NaN,2026-04-23,British Columbia,Burnaby,Hour,43.00,43.00
14,15495035,data analyst - informatics and systems,NaN,2026-04-24,Ontario,Oshawa,Hour,20.00,20.00
15,15500205,business data analyst,NaN,2026-04-27,Ontario,St. Thomas,Hour,41.50,41.50
16,15507639,data analyst - informatics and systems,NaN,2026-04-29,Alberta,Calgary,Hour,44.50,44.50
17,15514769,data quality analyst,NaN,2026-05-01,Ontario,Mississauga,Hour,44.50,44.50
18,15553278,data analyst - informatics and systems,NaN,2026-05-15,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00
19,15554294,data analyst - informatics and systems,NaN,2026-05-15,British Columbia,Surrey,Hour,45.00,45.00
20,15557280,data quality analyst,NaN,2026-05-17,Alberta,Fort McMurray,Hour,40.00,42.00
21,15559130,data analyst - informatics and systems,NaN,2026-05-19,Ontario,Toronto,Year,135000.00,140000.00
22,15566610,business data analyst,NaN,2026-05-20,Alberta,Edmonton,Hour,48.10,48.10
23,15597075,business intelligence specialist,NaN,2026-06-01,Ontario,Toronto,Hour,46.00,46.00
24,15601241,business data analyst,NaN,2026-06-02,Ontario,North York,Year,82810.00,82810.00
25,15605205,data analyst - informatics and systems,NaN,2026-06-03,Saskatchewan,Saskatoon,Hour,30.00,41.00
26,15604698,data analytics specialist,NaN,2026-06-03,Ontario,Toronto,Year,60000.00,75000.00
27,15628713,data scientist,NaN,2026-06-11,Ontario,Mississauga,Hour,45.00,55.00
28,15628476,business data analyst,NaN,2026-06-11,Alberta,Edmonton,Hour,46.00,48.00
29,15642551,data analytics specialist,NaN,2026-06-16,Ontario,NaN,Hour,35.00,35.00
30,15644785,data analyst - informatics and systems,NaN,2026-06-17,British Columbia,NaN,Year,62500.00,62500.00
31,15651841,data analyst - informatics and systems,NaN,2026-06-19,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00
32,15657440,business data analyst,NaN,2026-06-22,Ontario,North York,Year,80000.00,80000.00
33,15693882,data analyst - informatics and systems,NaN,2026-07-07,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00
34,15704901,data analyst - informatics and systems,NaN,2026-07-10,Ontario,Mississauga,Hour,45.00,45.00
35,15730915,data scientist,NaN,2026-07-21,Saskatchewan,Saskatoon,Year,69880.00,94544.00
36,15746387,data scientist,NaN,2026-07-28,Québec,Laval,Hour,41.91,49.10
37,15747768,data scientist,NaN,2026-07-28,New Brunswick,Shediac,Hour,42.00,45.00
38,15749186,business intelligence specialist,NaN,2026-07-29,Québec,Montréal,Hour,36.00,36.00
39,15752280,data analytics specialist,NaN,2026-07-30,Québec,Mirabel,Year,79000.00,82000.00
40,15752279,data analytics specialist,NaN,2026-07-30,Québec,Montréal,Year,79000.00,82000.00

In [102]:
# ==========================================
# DIRECT JOB BANK POSTINGS
# ==========================================

direct_jobs = technology_jobs_check[
    technology_jobs_check["External Indicator"] == 0
].copy()


print("Number of direct Job Bank postings:")
print(len(direct_jobs))


print("\nDirect postings by job title:")
print(
    direct_jobs["Job Title"]
    .value_counts()
)


print("\nDirect postings by province:")
print(
    direct_jobs["Province/Territory"]
    .value_counts()
)


print("\nDirect posting IDs:")
print(
    direct_jobs[
        [
            "WIC Job Location Snapshot ID",
            "Job Title",
            "Province/Territory",
            "City",
            "NOC21 Code"
        ]
    ]
    .to_string(index=False)
)

NameError: name 'technology_jobs_check' is not defined

In [ ]:
direct_jobs[
    [
        "WIC Job Location Snapshot ID",
        "Job Title",
        "Province/Territory",
        "City"
    ]
].head(5)

,WIC Job Location Snapshot ID,Job Title,Province/Territory,City
15014,15488194,data scientist,British Columbia,Burnaby
15016,15491326,business data analyst,British Columbia,Burnaby
21776,15376895,data scientist,New Brunswick,Shediac
23330,15495035,data analyst - informatics and systems,Ontario,Oshawa
27962,15507639,data analyst - informatics and systems,Alberta,Calgary

In [ ]:
direct_jobs.to_csv(
    "../data/processed/direct_job_bank_postings.csv",
    index=False
)

print("Saved direct Job Bank postings:")
print(direct_jobs.shape)

Saved direct Job Bank postings:
(41, 6)

In [ ]:


technology_collection = direct_jobs[
    [
        "WIC Job Location Snapshot ID",
        "Job Title",
        "First Posting Date",
        "Province/Territory",
        "City",
        "Salary Per",
        "Salary Minimum",
        "Salary Maximum"
    ]
].copy()


technology_collection = technology_collection.rename(
    columns={
        "WIC Job Location Snapshot ID": "WIC_ID",
        "Job Title": "Job_Title",
        "First Posting Date": "Posting_Date",
        "Province/Territory": "Province",
        "Salary Per": "Salary_Per",
        "Salary Minimum": "Salary_Minimum",
        "Salary Maximum": "Salary_Maximum"
    }
)



technology_collection["Job_Bank_Job_Number"] = pd.NA
technology_collection["Job_Bank_URL"] = pd.NA
technology_collection["Technology_Knowledge"] = pd.NA
technology_collection["Match_Status"] = "Not checked"


print("Technology collection template:")
print(technology_collection.shape)

display(technology_collection.head())




technology_collection.to_csv(
    "../data/processed/technology_collection.csv",
    index=False
)

print("\nSaved: technology_collection.csv")

KeyError: "['First Posting Date', 'Salary Per', 'Salary Minimum', 'Salary Maximum'] not in index"

In [ ]:


matching_batch = technology_collection[
    [
        "WIC_ID",
        "Job_Title",
        "Posting_Date",
        "Province",
        "City",
        "Salary_Per",
        "Salary_Minimum",
        "Salary_Maximum"
    ]
].head(5).copy()


# Create a useful search description for each posting
matching_batch["Search_Query"] = (
    matching_batch["Job_Title"].astype(str)
    + " "
    + matching_batch["City"].fillna("").astype(str)
    + " "
    + matching_batch["Province"].astype(str)
    + " Job Bank Canada"
)


print("FIRST MATCHING BATCH")
print("=" * 70)

for index, row in matching_batch.iterrows():

    print("\nWIC ID:", row["WIC_ID"])
    print("Job title:", row["Job_Title"])
    print("Date:", row["Posting_Date"])
    print("Location:", row["City"], ",", row["Province"])
    print(
        "Salary:",
        row["Salary_Minimum"],
        "-",
        row["Salary_Maximum"],
        row["Salary_Per"]
    )
    print("Search:", row["Search_Query"])
    print("-" * 70)

FIRST MATCHING BATCH
======================================================================

WIC ID: 15293390
Job title: marketing data analyst
Date: 2026-03-01 00:00:00
Location: Markham , Ontario
Salary: 48.0 - 48.0 Hour
Search: marketing data analyst Markham Ontario Job Bank Canada
----------------------------------------------------------------------

WIC ID: 15294248
Job title: data analyst - informatics and systems
Date: 2026-03-02 00:00:00
Location: Richmond Hill , Ontario
Salary: 45.0 - 45.0 Hour
Search: data analyst - informatics and systems Richmond Hill Ontario Job Bank Canada
----------------------------------------------------------------------

WIC ID: 15306899
Job title: data scientist
Date: 2026-03-06 00:00:00
Location: nan , Québec
Salary: 46.15 - 46.15 Hour
Search: data scientist  Québec Job Bank Canada
----------------------------------------------------------------------

WIC ID: 15323256
Job title: data scientist
Date: 2026-03-12 00:00:00
Location: Mississauga , Ontario
Salary: 98000.0 - 150000.0 Year
Search: data scientist Mississauga Ontario Job Bank Canada
----------------------------------------------------------------------

WIC ID: 15323309
Job title: data analyst - informatics and systems
Date: 2026-03-13 00:00:00
Location: Etobicoke , Ontario
Salary: 43.96 - 43.96 Hour
Search: data analyst - informatics and systems Etobicoke Ontario Job Bank Canada
----------------------------------------------------------------------

In [ ]:

mask = technology_collection["WIC_ID"] == 15293390

technology_collection.loc[mask, "Job_Bank_Job_Number"] = "3519121"
technology_collection.loc[mask, "Job_Bank_URL"] = (
    "https://www.jobbank.gc.ca/jobsearch/jobposting/49026134"
)
technology_collection.loc[mask, "Technology_Knowledge"] = (
    "Database management; Enterprise resource planning (ERP) software"
)
technology_collection.loc[mask, "Match_Status"] = "Verified"



mask = technology_collection["WIC_ID"] == 15294248

technology_collection.loc[mask, "Job_Bank_Job_Number"] = "3519430"
technology_collection.loc[mask, "Job_Bank_URL"] = (
    "https://www.jobbank.gc.ca/jobsearch/jobposting/49028849"
)


technology_collection.loc[mask, "Technology_Knowledge"] = ""
technology_collection.loc[mask, "Match_Status"] = "Verified"



mask = technology_collection["WIC_ID"] == 15323256

technology_collection.loc[mask, "Job_Bank_Job_Number"] = "3528614"
technology_collection.loc[mask, "Job_Bank_URL"] = (
    "https://www.jobbank.gc.ca/jobsearch/jobposting/49097871"
)
technology_collection.loc[mask, "Technology_Knowledge"] = (
    "Android; Data Warehouse; Linux; MySQL; "
    "Programming software; SASS"
)
technology_collection.loc[mask, "Match_Status"] = "Verified"



mask = technology_collection["WIC_ID"] == 15323309

technology_collection.loc[mask, "Job_Bank_Job_Number"] = "3528626"
technology_collection.loc[mask, "Job_Bank_URL"] = (
    "https://www.jobbank.gc.ca/jobsearch/jobposting/49098016"
)
technology_collection.loc[mask, "Technology_Knowledge"] = (
    "Android; Data Warehouse; Linux; MySQL; "
    "Programming software; SASS"
)
technology_collection.loc[mask, "Match_Status"] = "Verified"


mask = technology_collection["WIC_ID"] == 15306899

technology_collection.loc[mask, "Job_Bank_Job_Number"] = "3523161"
technology_collection.loc[mask, "Match_Status"] = "Needs verification"



technology_collection.to_csv(
    "../data/processed/technology_collection.csv",
    index=False
)


display(
    technology_collection[
        [
            "WIC_ID",
            "Job_Title",
            "Job_Bank_Job_Number",
            "Technology_Knowledge",
            "Match_Status"
        ]
    ].head(5)
)

print("\nMatch status:")
print(technology_collection["Match_Status"].value_counts())

,WIC_ID,Job_Title,Job_Bank_Job_Number,Technology_Knowledge,Match_Status
0,15293390,marketing data analyst,3519121,Database management; Enterprise resource plann...,Verified
1,15294248,data analyst - informatics and systems,3519430,,Verified
2,15306899,data scientist,3523161,<NA>,Needs verification
3,15323256,data scientist,3528614,Android; Data Warehouse; Linux; MySQL; Program...,Verified
4,15323309,data analyst - informatics and systems,3528626,Android; Data Warehouse; Linux; MySQL; Program...,Verified

Match status:
Match_Status
Not checked           36
Verified               4
Needs verification     1
Name: count, dtype: int64

In [ ]:


remaining_jobs = technology_collection[
    technology_collection["Match_Status"] == "Not checked"
].copy()

print("Remaining postings:", len(remaining_jobs))

display(
    remaining_jobs[
        [
            "WIC_ID",
            "Job_Title",
            "Posting_Date",
            "Province",
            "City",
            "Salary_Per",
            "Salary_Minimum",
            "Salary_Maximum"
        ]
    ]
)

Remaining postings: 36

,WIC_ID,Job_Title,Posting_Date,Province,City,Salary_Per,Salary_Minimum,Salary_Maximum
5,15323259,data analyst - informatics and systems,2026-03-13,Ontario,Mississauga,Hour,43.96,43.96
6,15341700,data scientist,2026-03-20,Ontario,NaN,Year,85000.00,95000.00
7,15342796,business data analyst,2026-03-20,Alberta,Edmonton,Hour,48.10,48.10
8,15342389,data analytics specialist,2026-03-20,Ontario,Cambridge,Hour,25.00,35.00
9,15355332,business data analyst,2026-03-25,Ontario,Nepean,Bi-weekly,3850.00,3850.00
10,15363720,data analytics specialist,2026-03-30,Ontario,Toronto,Year,80000.00,115000.00
11,15376895,data scientist,2026-04-03,New Brunswick,Shediac,Hour,42.00,45.00
12,15488194,data scientist,2026-04-22,British Columbia,Burnaby,Hour,48.10,48.10
13,15491326,business data analyst,2026-04-23,British Columbia,Burnaby,Hour,43.00,43.00
14,15495035,data analyst - informatics and systems,2026-04-24,Ontario,Oshawa,Hour,20.00,20.00
15,15500205,business data analyst,2026-04-27,Ontario,St. Thomas,Hour,41.50,41.50
16,15507639,data analyst - informatics and systems,2026-04-29,Alberta,Calgary,Hour,44.50,44.50
17,15514769,data quality analyst,2026-05-01,Ontario,Mississauga,Hour,44.50,44.50
18,15553278,data analyst - informatics and systems,2026-05-15,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00
19,15554294,data analyst - informatics and systems,2026-05-15,British Columbia,Surrey,Hour,45.00,45.00
20,15557280,data quality analyst,2026-05-17,Alberta,Fort McMurray,Hour,40.00,42.00
21,15559130,data analyst - informatics and systems,2026-05-19,Ontario,Toronto,Year,135000.00,140000.00
22,15566610,business data analyst,2026-05-20,Alberta,Edmonton,Hour,48.10,48.10
23,15597075,business intelligence specialist,2026-06-01,Ontario,Toronto,Hour,46.00,46.00
24,15601241,business data analyst,2026-06-02,Ontario,North York,Year,82810.00,82810.00
25,15605205,data analyst - informatics and systems,2026-06-03,Saskatchewan,Saskatoon,Hour,30.00,41.00
26,15604698,data analytics specialist,2026-06-03,Ontario,Toronto,Year,60000.00,75000.00
27,15628713,data scientist,2026-06-11,Ontario,Mississauga,Hour,45.00,55.00
28,15628476,business data analyst,2026-06-11,Alberta,Edmonton,Hour,46.00,48.00
29,15642551,data analytics specialist,2026-06-16,Ontario,NaN,Hour,35.00,35.00
30,15644785,data analyst - informatics and systems,2026-06-17,British Columbia,NaN,Year,62500.00,62500.00
31,15651841,data analyst - informatics and systems,2026-06-19,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00
32,15657440,business data analyst,2026-06-22,Ontario,North York,Year,80000.00,80000.00
33,15693882,data analyst - informatics and systems,2026-07-07,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00
34,15704901,data analyst - informatics and systems,2026-07-10,Ontario,Mississauga,Hour,45.00,45.00
35,15730915,data scientist,2026-07-21,Saskatchewan,Saskatoon,Year,69880.00,94544.00
36,15746387,data scientist,2026-07-28,Québec,Laval,Hour,41.91,49.10
37,15747768,data scientist,2026-07-28,New Brunswick,Shediac,Hour,42.00,45.00
38,15749186,business intelligence specialist,2026-07-29,Québec,Montréal,Hour,36.00,36.00
39,15752280,data analytics specialist,2026-07-30,Québec,Mirabel,Year,79000.00,82000.00
40,15752279,data analytics specialist,2026-07-30,Québec,Montréal,Year,79000.00,82000.00

In [ ]:
remaining_jobs[
    [
        "WIC_ID",
        "Job_Title",
        "Posting_Date",
        "Province",
        "City",
        "Salary_Per",
        "Salary_Minimum",
        "Salary_Maximum"
    ]
].to_csv(
    "../data/processed/remaining_technology_jobs.csv",
    index=False
)

print("Saved remaining_technology_jobs.csv")
print("Rows:", len(remaining_jobs))

Saved remaining_technology_jobs.csv
Rows: 36

In [ ]:


def add_job_match(
    wic_id,
    job_bank_number,
    job_bank_url,
    technologies,
    status="Verified"
):
    """
    Adds verified Job Bank information to one posting
    in technology_collection.
    """

    mask = technology_collection["WIC_ID"] == wic_id

    technology_collection.loc[
        mask,
        "Job_Bank_Job_Number"
    ] = str(job_bank_number)

    technology_collection.loc[
        mask,
        "Job_Bank_URL"
    ] = job_bank_url

    technology_collection.loc[
        mask,
        "Technology_Knowledge"
    ] = technologies

    technology_collection.loc[
        mask,
        "Match_Status"
    ] = status


def save_technology_progress():

    technology_collection.to_csv(
        "../data/processed/technology_collection.csv",
        index=False
    )

    print("Progress saved!")

    print("\nMATCH STATUS")
    print(
        technology_collection[
            "Match_Status"
        ].value_counts()
    )

In [ ]:


add_job_match(
    wic_id=15601241,
    job_bank_number="3589827",
    job_bank_url="https://www.jobbank.gc.ca/jobsearch/jobposting/49637471",
    technologies="C; C++; Java; Python",
    status="Verified"
)



add_job_match(
    wic_id=15554294,
    job_bank_number="3577305",
    job_bank_url="https://www.jobbank.gc.ca/jobsearch/jobposting/49522430",
    technologies="",
    status="Verified - No technology listed"
)



add_job_match(
    wic_id=15605205,
    job_bank_number="3587624",
    job_bank_url="https://www.jobbank.gc.ca/jobsearch/jobposting/49645685",
    technologies="",
    status="Verified - No technology listed"
)



add_job_match(
    wic_id=15644785,
    job_bank_number="3590100",
    job_bank_url="https://www.jobbank.gc.ca/jobsearch/jobposting/49736034",
    technologies=(
        "Data analysis software; "
        "Amazon Web Services (AWS); "
        "Python; "
        "Business intelligence; "
        "Data analysis and interpretation"
    ),
    status="Verified"
)



add_job_match(
    wic_id=15704901,
    job_bank_number="3619186",
    job_bank_url="https://www.jobbank.gc.ca/jobsearch/jobposting/49878693",
    technologies=(
        "Data Warehouse; "
        "Programming software; "
        "Database software; "
        "Spreadsheet; "
        "SASS; "
        "SQL"
    ),
    status="Verified"
)


save_technology_progress()


display(
    technology_collection[
        technology_collection["WIC_ID"].isin(
            [
                15601241,
                15554294,
                15605205,
                15644785,
                15704901
            ]
        )
    ][
        [
            "WIC_ID",
            "Job_Title",
            "Job_Bank_Job_Number",
            "Technology_Knowledge",
            "Match_Status"
        ]
    ]
)

Progress saved!

MATCH STATUS
Match_Status
Not checked                        31
Verified                            7
Verified - No technology listed     2
Needs verification                  1
Name: count, dtype: int64

,WIC_ID,Job_Title,Job_Bank_Job_Number,Technology_Knowledge,Match_Status
19,15554294,data analyst - informatics and systems,3577305,,Verified - No technology listed
24,15601241,business data analyst,3589827,C; C++; Java; Python,Verified
25,15605205,data analyst - informatics and systems,3587624,,Verified - No technology listed
30,15644785,data analyst - informatics and systems,3590100,Data analysis software; Amazon Web Services (A...,Verified
34,15704901,data analyst - informatics and systems,3619186,Data Warehouse; Programming software; Database...,Verified

In [ ]:
import os

print(
    os.listdir(
        "../data/processed"
    )
)

['canada_data_jobs_clean.csv', 'direct_job_bank_postings.csv', 'jobs_with_skills.csv', 'job_market.db', 'noc_skill_profiles.csv', 'remaining_technology_jobs.csv', 'skill_summary.csv', 'technology_collection.csv', 'technology_demand.csv', 'technology_mentions.csv']

In [ ]:


add_job_match(
    wic_id=15342389,
    job_bank_number="3531046",
    job_bank_url="https://mb.jobbank.gc.ca/jobsearch/jobposting/49144423",
    technologies="",
    status="Verified - No technology listed"
)


add_job_match(
    wic_id=15341700,
    job_bank_number="3523745",
    job_bank_url="",
    technologies="",
    status="Verified - No technology listed"
)



add_job_match(
    wic_id=15376895,
    job_bank_number="3544474",
    job_bank_url="",
    technologies=(
        "Machine Learning; "
        "SQL; "
        "Mapping and data visualization software; "
        "Data analysis software; "
        "Python; "
        "Big Data"
    ),
    status="Verified"
)



add_job_match(
    wic_id=15488194,
    job_bank_number="3559548",
    job_bank_url="",
    technologies="",
    status="Verified - No technology listed"
)



save_technology_progress()


print("\nUPDATED MATCH STATUS")

print(
    technology_collection[
        "Match_Status"
    ].value_counts()
)


display(
    technology_collection[
        technology_collection["WIC_ID"].isin(
            [
                15342389,
                15341700,
                15376895,
                15488194
            ]
        )
    ][
        [
            "WIC_ID",
            "Job_Title",
            "Job_Bank_Job_Number",
            "Technology_Knowledge",
            "Match_Status"
        ]
    ]
)

Progress saved!

MATCH STATUS
Match_Status
Not checked                        27
Verified                            8
Verified - No technology listed     5
Needs verification                  1
Name: count, dtype: int64

UPDATED MATCH STATUS
Match_Status
Not checked                        27
Verified                            8
Verified - No technology listed     5
Needs verification                  1
Name: count, dtype: int64

,WIC_ID,Job_Title,Job_Bank_Job_Number,Technology_Knowledge,Match_Status
6,15341700,data scientist,3523745,,Verified - No technology listed
8,15342389,data analytics specialist,3531046,,Verified - No technology listed
11,15376895,data scientist,3544474,Machine Learning; SQL; Mapping and data visual...,Verified
12,15488194,data scientist,3559548,,Verified - No technology listed

In [ ]:


remaining_jobs = technology_collection[
    technology_collection["Match_Status"].isin(
        [
            "Not checked",
            "Needs verification"
        ]
    )
].copy()

remaining_jobs = remaining_jobs.sort_values(
    "Posting_Date"
)

print("Remaining postings:", len(remaining_jobs))

display(
    remaining_jobs[
        [
            "WIC_ID",
            "Job_Title",
            "Posting_Date",
            "Province",
            "City",
            "Salary_Per",
            "Salary_Minimum",
            "Salary_Maximum",
            "Match_Status"
        ]
    ]
)

Remaining postings: 28

,WIC_ID,Job_Title,Posting_Date,Province,City,Salary_Per,Salary_Minimum,Salary_Maximum,Match_Status
2,15306899,data scientist,2026-03-06,Québec,NaN,Hour,46.15,46.15,Needs verification
5,15323259,data analyst - informatics and systems,2026-03-13,Ontario,Mississauga,Hour,43.96,43.96,Not checked
7,15342796,business data analyst,2026-03-20,Alberta,Edmonton,Hour,48.10,48.10,Not checked
9,15355332,business data analyst,2026-03-25,Ontario,Nepean,Bi-weekly,3850.00,3850.00,Not checked
10,15363720,data analytics specialist,2026-03-30,Ontario,Toronto,Year,80000.00,115000.00,Not checked
13,15491326,business data analyst,2026-04-23,British Columbia,Burnaby,Hour,43.00,43.00,Not checked
14,15495035,data analyst - informatics and systems,2026-04-24,Ontario,Oshawa,Hour,20.00,20.00,Not checked
15,15500205,business data analyst,2026-04-27,Ontario,St. Thomas,Hour,41.50,41.50,Not checked
16,15507639,data analyst - informatics and systems,2026-04-29,Alberta,Calgary,Hour,44.50,44.50,Not checked
17,15514769,data quality analyst,2026-05-01,Ontario,Mississauga,Hour,44.50,44.50,Not checked
18,15553278,data analyst - informatics and systems,2026-05-15,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00,Not checked
20,15557280,data quality analyst,2026-05-17,Alberta,Fort McMurray,Hour,40.00,42.00,Not checked
21,15559130,data analyst - informatics and systems,2026-05-19,Ontario,Toronto,Year,135000.00,140000.00,Not checked
22,15566610,business data analyst,2026-05-20,Alberta,Edmonton,Hour,48.10,48.10,Not checked
23,15597075,business intelligence specialist,2026-06-01,Ontario,Toronto,Hour,46.00,46.00,Not checked
26,15604698,data analytics specialist,2026-06-03,Ontario,Toronto,Year,60000.00,75000.00,Not checked
27,15628713,data scientist,2026-06-11,Ontario,Mississauga,Hour,45.00,55.00,Not checked
28,15628476,business data analyst,2026-06-11,Alberta,Edmonton,Hour,46.00,48.00,Not checked
29,15642551,data analytics specialist,2026-06-16,Ontario,NaN,Hour,35.00,35.00,Not checked
31,15651841,data analyst - informatics and systems,2026-06-19,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00,Not checked
32,15657440,business data analyst,2026-06-22,Ontario,North York,Year,80000.00,80000.00,Not checked
33,15693882,data analyst - informatics and systems,2026-07-07,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00,Not checked
35,15730915,data scientist,2026-07-21,Saskatchewan,Saskatoon,Year,69880.00,94544.00,Not checked
36,15746387,data scientist,2026-07-28,Québec,Laval,Hour,41.91,49.10,Not checked
37,15747768,data scientist,2026-07-28,New Brunswick,Shediac,Hour,42.00,45.00,Not checked
38,15749186,business intelligence specialist,2026-07-29,Québec,Montréal,Hour,36.00,36.00,Not checked
39,15752280,data analytics specialist,2026-07-30,Québec,Mirabel,Year,79000.00,82000.00,Not checked
40,15752279,data analytics specialist,2026-07-30,Québec,Montréal,Year,79000.00,82000.00,Not checked

In [ ]:


remaining_jobs = technology_collection[
    technology_collection["Match_Status"].isin(
        [
            "Not checked",
            "Needs verification"
        ]
    )
].copy()


remaining_jobs = remaining_jobs.sort_values(
    "Posting_Date"
).reset_index(drop=True)



def create_search_query(row):

    city = ""

    if pd.notna(row["City"]):
        city = str(row["City"])

    query = (
        f'{row["Job_Title"]} '
        f'{city} '
        f'{row["Province"]} '
        f'Job Bank Canada '
        f'{row["Salary_Minimum"]}'
    )

    return " ".join(query.split())


remaining_jobs["Search_Query"] = remaining_jobs.apply(
    create_search_query,
    axis=1
)


print("Remaining jobs:", len(remaining_jobs))

print("\nFIRST 10 SEARCHES")
print("=" * 80)


for index, row in remaining_jobs.head(10).iterrows():

    print("\nWIC ID:", row["WIC_ID"])
    print("Job title:", row["Job_Title"])
    print("Date:", row["Posting_Date"])
    print("Location:", row["City"], ",", row["Province"])

    print(
        "Salary:",
        row["Salary_Minimum"],
        "-",
        row["Salary_Maximum"],
        row["Salary_Per"]
    )

    print("\nSEARCH THIS:")
    print(row["Search_Query"])

    print("-" * 80)

Remaining jobs: 28

FIRST 10 SEARCHES
================================================================================

WIC ID: 15306899
Job title: data scientist
Date: 2026-03-06 00:00:00
Location: nan , Québec
Salary: 46.15 - 46.15 Hour

SEARCH THIS:
data scientist Québec Job Bank Canada 46.15
--------------------------------------------------------------------------------

WIC ID: 15323259
Job title: data analyst - informatics and systems
Date: 2026-03-13 00:00:00
Location: Mississauga , Ontario
Salary: 43.96 - 43.96 Hour

SEARCH THIS:
data analyst - informatics and systems Mississauga Ontario Job Bank Canada 43.96
--------------------------------------------------------------------------------

WIC ID: 15342796
Job title: business data analyst
Date: 2026-03-20 00:00:00
Location: Edmonton , Alberta
Salary: 48.1 - 48.1 Hour

SEARCH THIS:
business data analyst Edmonton Alberta Job Bank Canada 48.1
--------------------------------------------------------------------------------

WIC ID: 15355332
Job title: business data analyst
Date: 2026-03-25 00:00:00
Location: Nepean , Ontario
Salary: 3850.0 - 3850.0 Bi-weekly

SEARCH THIS:
business data analyst Nepean Ontario Job Bank Canada 3850.0
--------------------------------------------------------------------------------

WIC ID: 15363720
Job title: data analytics specialist
Date: 2026-03-30 00:00:00
Location: Toronto , Ontario
Salary: 80000.0 - 115000.0 Year

SEARCH THIS:
data analytics specialist Toronto Ontario Job Bank Canada 80000.0
--------------------------------------------------------------------------------

WIC ID: 15491326
Job title: business data analyst
Date: 2026-04-23 00:00:00
Location: Burnaby , British Columbia
Salary: 43.0 - 43.0 Hour

SEARCH THIS:
business data analyst Burnaby British Columbia Job Bank Canada 43.0
--------------------------------------------------------------------------------

WIC ID: 15495035
Job title: data analyst - informatics and systems
Date: 2026-04-24 00:00:00
Location: Oshawa , Ontario
Salary: 20.0 - 20.0 Hour

SEARCH THIS:
data analyst - informatics and systems Oshawa Ontario Job Bank Canada 20.0
--------------------------------------------------------------------------------

WIC ID: 15500205
Job title: business data analyst
Date: 2026-04-27 00:00:00
Location: St. Thomas , Ontario
Salary: 41.5 - 41.5 Hour

SEARCH THIS:
business data analyst St. Thomas Ontario Job Bank Canada 41.5
--------------------------------------------------------------------------------

WIC ID: 15507639
Job title: data analyst - informatics and systems
Date: 2026-04-29 00:00:00
Location: Calgary , Alberta
Salary: 44.5 - 44.5 Hour

SEARCH THIS:
data analyst - informatics and systems Calgary Alberta Job Bank Canada 44.5
--------------------------------------------------------------------------------

WIC ID: 15514769
Job title: data quality analyst
Date: 2026-05-01 00:00:00
Location: Mississauga , Ontario
Salary: 44.5 - 44.5 Hour

SEARCH THIS:
data quality analyst Mississauga Ontario Job Bank Canada 44.5
--------------------------------------------------------------------------------

In [ ]:


add_job_match(
    wic_id=15323259,
    job_bank_number="3528622",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)



add_job_match(
    wic_id=15507639,
    job_bank_number="3558975",
    job_bank_url="https://www.jobbank.gc.ca/jobsearch/jobposting/49422699",
    technologies=(
        "Machine Learning; "
        "Microsoft Visual Studio; "
        "DB2; "
        "MySQL; "
        "Mapping and data visualization software; "
        "Data analysis software; "
        "MS Office; "
        "MS Windows; "
        "Spreadsheet; "
        "Amazon Web Services (AWS)"
    ),
    status="Verified"
)



add_job_match(
    wic_id=15559130,
    job_bank_number="3575653",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)



add_job_match(
    wic_id=15657440,
    job_bank_number="3596666",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)


save_technology_progress()


print("\nUPDATED STATUS")

print(
    technology_collection[
        "Match_Status"
    ].value_counts()
)

Progress saved!

MATCH STATUS
Match_Status
Not checked                        23
Verified                            9
Verified - No technology listed     5
Needs technology review             3
Needs verification                  1
Name: count, dtype: int64

UPDATED STATUS
Match_Status
Not checked                        23
Verified                            9
Verified - No technology listed     5
Needs technology review             3
Needs verification                  1
Name: count, dtype: int64

In [ ]:


import pandas as pd
import re


verified_technology_jobs = technology_collection[
    technology_collection["Match_Status"].isin(
        [
            "Verified",
            "Verified - No technology listed"
        ]
    )
].copy()

print("Verified direct Job Bank postings:")
print(len(verified_technology_jobs))



verified_technology_jobs["Technology_Knowledge"] = (
    verified_technology_jobs["Technology_Knowledge"]
    .fillna("")
    .astype(str)
)


technology_patterns = {

    "Python": [
        r"\bpython\b"
    ],

    # Only count SQL when SQL itself is explicitly mentioned
    "SQL": [
        r"(?<![a-zA-Z])sql(?![a-zA-Z])"
    ],

    "MySQL": [
        r"\bmysql\b"
    ],

    "Excel": [
        r"\bexcel\b",
        r"\bmicrosoft excel\b",
        r"\bms excel\b"
    ],

    "Power BI": [
        r"\bpower\s*bi\b",
        r"\bpowerbi\b"
    ],

    "Tableau": [
        r"\btableau\b"
    ],

    "R": [
        r"\br programming\b",
        r"\br language\b"
    ],

    "AWS": [
        r"\baws\b",
        r"\bamazon web services\b"
    ],

    "Azure": [
        r"\bazure\b",
        r"\bmicrosoft azure\b"
    ],

    "C": [
        r"(?<!\+)\bc\b(?!\+)"
    ],

    # Correct pattern for C++
    "C++": [
        r"(?<!\w)c\+\+(?!\w)"
    ],

    "Java": [
        r"\bjava\b"
    ],

    "Spark": [
        r"\bapache spark\b",
        r"\bspark\b"
    ],

    "Databricks": [
        r"\bdatabricks\b"
    ],

    "Snowflake": [
        r"\bsnowflake\b"
    ],

    "SAS": [
        r"\bsas\b"
    ],

    "SASS": [
        r"\bsass\b"
    ],

    "Linux": [
        r"\blinux\b"
    ],

    "Git": [
        r"\bgit\b",
        r"\bgithub\b",
        r"\bgitlab\b"
    ],

    "Machine Learning": [
        r"\bmachine learning\b"
    ],

    "Big Data": [
        r"\bbig data\b"
    ],

    "Data Warehouse": [
        r"\bdata warehouse\b"
    ],

    "DB2": [
        r"\bdb2\b"
    ],

    "Visual Studio": [
        r"\bvisual studio\b"
    ],

    "ERP Software": [
        r"\benterprise resource planning\b",
        r"\berp\b"
    ]
}



for technology, patterns in technology_patterns.items():

    combined_pattern = "|".join(patterns)

    verified_technology_jobs[technology] = (
        verified_technology_jobs["Technology_Knowledge"]
        .str.contains(
            combined_pattern,
            case=False,
            regex=True,
            na=False
        )
        .astype(int)
    )



technology_results = []

total_verified = len(verified_technology_jobs)


for technology in technology_patterns.keys():

    mentions = int(
        verified_technology_jobs[technology].sum()
    )

    if total_verified > 0:
        percentage = (
            mentions / total_verified
        ) * 100
    else:
        percentage = 0

    technology_results.append(
        {
            "Technology": technology,
            "Postings_Mentioning": mentions,
            "Demand_Percentage": round(
                percentage,
                2
            )
        }
    )


technology_demand = pd.DataFrame(
    technology_results
)


technology_demand = (
    technology_demand
    .sort_values(
        [
            "Postings_Mentioning",
            "Technology"
        ],
        ascending=[
            False,
            True
        ]
    )
    .reset_index(drop=True)
)


technology_demand_nonzero = (
    technology_demand[
        technology_demand[
            "Postings_Mentioning"
        ] > 0
    ]
    .reset_index(drop=True)
)



print("\nTECHNOLOGY DEMAND")

print(
    "Denominator:",
    total_verified,
    "verified direct Job Bank postings"
)

display(
    technology_demand_nonzero
)



verified_technology_jobs.to_csv(
    "../data/processed/technology_mentions.csv",
    index=False
)

technology_demand.to_csv(
    "../data/processed/technology_demand.csv",
    index=False
)


print("\nSaved:")
print("technology_mentions.csv")
print("technology_demand.csv")

Verified direct Job Bank postings:
14

TECHNOLOGY DEMAND
Denominator: 14 verified direct Job Bank postings

          Technology  Postings_Mentioning  Demand_Percentage
0     Data Warehouse                    3              21.43
1              MySQL                    3              21.43
2             Python                    3              21.43
3               SASS                    3              21.43
4                AWS                    2              14.29
5              Linux                    2              14.29
6   Machine Learning                    2              14.29
7                SQL                    2              14.29
8           Big Data                    1               7.14
9                  C                    1               7.14
10               C++                    1               7.14
11               DB2                    1               7.14
12      ERP Software                    1               7.14
13              Java                    1               7.14
14     Visual Studio                    1               7.14

Saved:
technology_mentions.csv
technology_demand.csv

In [ ]:


import pandas as pd



verification_queue = technology_collection[
    ~technology_collection["Match_Status"].isin(
        [
            "Verified",
            "Verified - No technology listed"
        ]
    )
].copy()


priority_order = {
    "Needs technology review": 1,
    "Needs verification": 2,
    "Not checked": 3
}

verification_queue["Priority"] = (
    verification_queue["Match_Status"]
    .map(priority_order)
)


verification_queue = (
    verification_queue
    .sort_values(
        ["Priority", "Posting_Date"]
    )
    .reset_index(drop=True)
)



def build_search_query(row):

    parts = [
        str(row["Job_Title"])
    ]

    if pd.notna(row["City"]):
        parts.append(str(row["City"]))

    if pd.notna(row["Province"]):
        parts.append(str(row["Province"]))

    parts.append("Job Bank Canada")

    if pd.notna(row["Salary_Minimum"]):
        parts.append(str(row["Salary_Minimum"]))

    return " ".join(parts)


verification_queue["Search_Query"] = (
    verification_queue.apply(
        build_search_query,
        axis=1
    )
)



print("=" * 70)
print("FINAL TECHNOLOGY VERIFICATION QUEUE")
print("=" * 70)

print(
    "\nJobs still requiring work:",
    len(verification_queue)
)

print("\nSTATUS:")
print(
    verification_queue[
        "Match_Status"
    ].value_counts()
)


print("\nNEXT 10 JOBS TO RESOLVE:")

display(
    verification_queue[
        [
            "WIC_ID",
            "Job_Title",
            "Posting_Date",
            "Province",
            "City",
            "Salary_Per",
            "Salary_Minimum",
            "Salary_Maximum",
            "Job_Bank_Job_Number",
            "Match_Status",
            "Search_Query"
        ]
    ].head(10)
)

======================================================================
FINAL TECHNOLOGY VERIFICATION QUEUE
======================================================================

Jobs still requiring work: 27

STATUS:
Match_Status
Not checked                23
Needs technology review     3
Needs verification          1
Name: count, dtype: int64

NEXT 10 JOBS TO RESOLVE:

,WIC_ID,Job_Title,Posting_Date,Province,City,Salary_Per,Salary_Minimum,Salary_Maximum,Job_Bank_Job_Number,Match_Status,Search_Query
0,15323259,data analyst - informatics and systems,2026-03-13,Ontario,Mississauga,Hour,43.96,43.96,3528622,Needs technology review,data analyst - informatics and systems Mississ...
1,15559130,data analyst - informatics and systems,2026-05-19,Ontario,Toronto,Year,135000.00,140000.00,3575653,Needs technology review,data analyst - informatics and systems Toronto...
2,15657440,business data analyst,2026-06-22,Ontario,North York,Year,80000.00,80000.00,3596666,Needs technology review,business data analyst North York Ontario Job B...
3,15306899,data scientist,2026-03-06,Québec,NaN,Hour,46.15,46.15,3523161,Needs verification,data scientist Québec Job Bank Canada 46.15
4,15342796,business data analyst,2026-03-20,Alberta,Edmonton,Hour,48.10,48.10,<NA>,Not checked,business data analyst Edmonton Alberta Job Ban...
5,15355332,business data analyst,2026-03-25,Ontario,Nepean,Bi-weekly,3850.00,3850.00,<NA>,Not checked,business data analyst Nepean Ontario Job Bank ...
6,15363720,data analytics specialist,2026-03-30,Ontario,Toronto,Year,80000.00,115000.00,<NA>,Not checked,data analytics specialist Toronto Ontario Job ...
7,15491326,business data analyst,2026-04-23,British Columbia,Burnaby,Hour,43.00,43.00,<NA>,Not checked,business data analyst Burnaby British Columbia...
8,15495035,data analyst - informatics and systems,2026-04-24,Ontario,Oshawa,Hour,20.00,20.00,<NA>,Not checked,data analyst - informatics and systems Oshawa ...
9,15500205,business data analyst,2026-04-27,Ontario,St. Thomas,Hour,41.50,41.50,<NA>,Not checked,business data analyst St. Thomas Ontario Job B...

In [ ]:


unchecked_jobs = technology_collection[
    technology_collection["Match_Status"] == "Not checked"
].copy()


unchecked_jobs = unchecked_jobs.sort_values(
    "Posting_Date"
).reset_index(drop=True)


print("Unchecked postings:", len(unchecked_jobs))



display(
    unchecked_jobs[
        [
            "WIC_ID",
            "Job_Title",
            "Posting_Date",
            "Province",
            "City",
            "Salary_Per",
            "Salary_Minimum",
            "Salary_Maximum"
        ]
    ].head(10)
)

Unchecked postings: 23

,WIC_ID,Job_Title,Posting_Date,Province,City,Salary_Per,Salary_Minimum,Salary_Maximum
0,15342796,business data analyst,2026-03-20,Alberta,Edmonton,Hour,48.1,48.1
1,15355332,business data analyst,2026-03-25,Ontario,Nepean,Bi-weekly,3850.0,3850.0
2,15363720,data analytics specialist,2026-03-30,Ontario,Toronto,Year,80000.0,115000.0
3,15491326,business data analyst,2026-04-23,British Columbia,Burnaby,Hour,43.0,43.0
4,15495035,data analyst - informatics and systems,2026-04-24,Ontario,Oshawa,Hour,20.0,20.0
5,15500205,business data analyst,2026-04-27,Ontario,St. Thomas,Hour,41.5,41.5
6,15514769,data quality analyst,2026-05-01,Ontario,Mississauga,Hour,44.5,44.5
7,15553278,data analyst - informatics and systems,2026-05-15,Québec,Stoneham-et-Tewkesbury,Hour,40.0,40.0
8,15557280,data quality analyst,2026-05-17,Alberta,Fort McMurray,Hour,40.0,42.0
9,15566610,business data analyst,2026-05-20,Alberta,Edmonton,Hour,48.1,48.1

In [ ]:


add_job_match(
    wic_id=15342796,
    job_bank_number="3534366",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)



add_job_match(
    wic_id=15355332,
    job_bank_number="3538057",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)


add_job_match(
    wic_id=15363720,
    job_bank_number="3532652",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)



add_job_match(
    wic_id=15495035,
    job_bank_number="3561054",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)



add_job_match(
    wic_id=15500205,
    job_bank_number="3543452",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)



add_job_match(
    wic_id=15514769,
    job_bank_number="3566016",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)


add_job_match(
    wic_id=15553278,
    job_bank_number="3569127",
    job_bank_url="",
    technologies=(
        "MS SQL Server; "
        "Progress; "
        "Java; "
        "Python; "
        "SQL"
    ),
    status="Verified"
)



add_job_match(
    wic_id=15557280,
    job_bank_number="3577992",
    job_bank_url="",
    technologies="",
    status="Needs technology review"
)


save_technology_progress()


print("\nUPDATED MATCH STATUS")

print(
    technology_collection[
        "Match_Status"
    ].value_counts()
)

Progress saved!

MATCH STATUS
Match_Status
Not checked                        15
Verified                           10
Needs technology review            10
Verified - No technology listed     5
Needs verification                  1
Name: count, dtype: int64

UPDATED MATCH STATUS
Match_Status
Not checked                        15
Verified                           10
Needs technology review            10
Verified - No technology listed     5
Needs verification                  1
Name: count, dtype: int64

In [ ]:

final_unchecked = technology_collection[
    technology_collection["Match_Status"] == "Not checked"
].copy()

final_unchecked = final_unchecked.sort_values(
    "Posting_Date"
).reset_index(drop=True)

print("Final unchecked postings:")
print(len(final_unchecked))

display(
    final_unchecked[
        [
            "WIC_ID",
            "Job_Title",
            "Posting_Date",
            "Province",
            "City",
            "Salary_Per",
            "Salary_Minimum",
            "Salary_Maximum"
        ]
    ]
)

final_unchecked[
    [
        "WIC_ID",
        "Job_Title",
        "Posting_Date",
        "Province",
        "City",
        "Salary_Per",
        "Salary_Minimum",
        "Salary_Maximum"
    ]
].to_csv(
    "../data/processed/final_unchecked_technology_jobs.csv",
    index=False
)

print("\nSaved: final_unchecked_technology_jobs.csv")

Final unchecked postings:
15

,WIC_ID,Job_Title,Posting_Date,Province,City,Salary_Per,Salary_Minimum,Salary_Maximum
0,15491326,business data analyst,2026-04-23,British Columbia,Burnaby,Hour,43.00,43.0
1,15566610,business data analyst,2026-05-20,Alberta,Edmonton,Hour,48.10,48.1
2,15597075,business intelligence specialist,2026-06-01,Ontario,Toronto,Hour,46.00,46.0
3,15604698,data analytics specialist,2026-06-03,Ontario,Toronto,Year,60000.00,75000.0
4,15628713,data scientist,2026-06-11,Ontario,Mississauga,Hour,45.00,55.0
5,15628476,business data analyst,2026-06-11,Alberta,Edmonton,Hour,46.00,48.0
6,15642551,data analytics specialist,2026-06-16,Ontario,NaN,Hour,35.00,35.0
7,15651841,data analyst - informatics and systems,2026-06-19,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.0
8,15693882,data analyst - informatics and systems,2026-07-07,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.0
9,15730915,data scientist,2026-07-21,Saskatchewan,Saskatoon,Year,69880.00,94544.0
10,15746387,data scientist,2026-07-28,Québec,Laval,Hour,41.91,49.1
11,15747768,data scientist,2026-07-28,New Brunswick,Shediac,Hour,42.00,45.0
12,15749186,business intelligence specialist,2026-07-29,Québec,Montréal,Hour,36.00,36.0
13,15752280,data analytics specialist,2026-07-30,Québec,Mirabel,Year,79000.00,82000.0
14,15752279,data analytics specialist,2026-07-30,Québec,Montréal,Year,79000.00,82000.0

Saved: final_unchecked_technology_jobs.csv

In [ ]:

technology_review_jobs = technology_collection[
    technology_collection["Match_Status"]
    == "Needs technology review"
].copy()


technology_review_jobs = (
    technology_review_jobs
    .sort_values("Posting_Date")
    .reset_index(drop=True)
)


print(
    "Postings needing technology review:",
    len(technology_review_jobs)
)


display(
    technology_review_jobs[
        [
            "WIC_ID",
            "Job_Title",
            "Posting_Date",
            "Province",
            "City",
            "Salary_Per",
            "Salary_Minimum",
            "Salary_Maximum",
            "Job_Bank_Job_Number"
        ]
    ]
)

Postings needing technology review: 10

,WIC_ID,Job_Title,Posting_Date,Province,City,Salary_Per,Salary_Minimum,Salary_Maximum,Job_Bank_Job_Number
0,15323259,data analyst - informatics and systems,2026-03-13,Ontario,Mississauga,Hour,43.96,43.96,3528622
1,15342796,business data analyst,2026-03-20,Alberta,Edmonton,Hour,48.10,48.10,3534366
2,15355332,business data analyst,2026-03-25,Ontario,Nepean,Bi-weekly,3850.00,3850.00,3538057
3,15363720,data analytics specialist,2026-03-30,Ontario,Toronto,Year,80000.00,115000.00,3532652
4,15495035,data analyst - informatics and systems,2026-04-24,Ontario,Oshawa,Hour,20.00,20.00,3561054
5,15500205,business data analyst,2026-04-27,Ontario,St. Thomas,Hour,41.50,41.50,3543452
6,15514769,data quality analyst,2026-05-01,Ontario,Mississauga,Hour,44.50,44.50,3566016
7,15557280,data quality analyst,2026-05-17,Alberta,Fort McMurray,Hour,40.00,42.00,3577992
8,15559130,data analyst - informatics and systems,2026-05-19,Ontario,Toronto,Year,135000.00,140000.00,3575653
9,15657440,business data analyst,2026-06-22,Ontario,North York,Year,80000.00,80000.00,3596666

In [ ]:

add_job_match(
    wic_id=15323259,
    job_bank_number="3528622",
    job_bank_url="https://yt.jobbank.gc.ca/jobsearch/jobposting/49097876",
    technologies=(
        "Data Warehouse; "
        "Linux; "
        "MySQL; "
        "Programming software; "
        "SASS"
    ),
    status="Verified"
)



add_job_match(
    wic_id=15355332,
    job_bank_number="3538057",
    job_bank_url="https://www.jobbank.gc.ca/jobsearch/jobposting/49175818",
    technologies=(
        "Agile; "
        "Cloud; "
        "Informatica; "
        "Networking software; "
        "Networking security; "
        "Intranet; "
        "Database software; "
        "Software development; "
        "Spreadsheet; "
        "MS Office"
    ),
    status="Verified"
)



add_job_match(
    wic_id=15559130,
    job_bank_number="3575653",
    job_bank_url="https://www.jobbank.gc.ca/jobsearch/jobposting/49541388",
    technologies=(
        "Informix; "
        "Oracle"
    ),
    status="Verified"
)



save_technology_progress()



print("\nUPDATED MATCH STATUS")

print(
    technology_collection[
        "Match_Status"
    ].value_counts()
)


print("\nPostings still needing technology review:")

print(
    len(
        technology_collection[
            technology_collection["Match_Status"]
            == "Needs technology review"
        ]
    )
)

Progress saved!

MATCH STATUS
Match_Status
Not checked                        15
Verified                           13
Needs technology review             7
Verified - No technology listed     5
Needs verification                  1
Name: count, dtype: int64

UPDATED MATCH STATUS
Match_Status
Not checked                        15
Verified                           13
Needs technology review             7
Verified - No technology listed     5
Needs verification                  1
Name: count, dtype: int64

Postings still needing technology review:
7

In [ ]:


final_technology_review = technology_collection[
    technology_collection["Match_Status"]
    == "Needs technology review"
].copy()

final_technology_review = (
    final_technology_review
    .sort_values("Posting_Date")
    .reset_index(drop=True)
)

print(
    "Technology-review postings remaining:",
    len(final_technology_review)
)

display(
    final_technology_review[
        [
            "WIC_ID",
            "Job_Title",
            "Posting_Date",
            "Province",
            "City",
            "Salary_Per",
            "Salary_Minimum",
            "Salary_Maximum",
            "Job_Bank_Job_Number"
        ]
    ]
)

Technology-review postings remaining: 7

,WIC_ID,Job_Title,Posting_Date,Province,City,Salary_Per,Salary_Minimum,Salary_Maximum,Job_Bank_Job_Number
0,15342796,business data analyst,2026-03-20,Alberta,Edmonton,Hour,48.1,48.1,3534366
1,15363720,data analytics specialist,2026-03-30,Ontario,Toronto,Year,80000.0,115000.0,3532652
2,15495035,data analyst - informatics and systems,2026-04-24,Ontario,Oshawa,Hour,20.0,20.0,3561054
3,15500205,business data analyst,2026-04-27,Ontario,St. Thomas,Hour,41.5,41.5,3543452
4,15514769,data quality analyst,2026-05-01,Ontario,Mississauga,Hour,44.5,44.5,3566016
5,15557280,data quality analyst,2026-05-17,Alberta,Fort McMurray,Hour,40.0,42.0,3577992
6,15657440,business data analyst,2026-06-22,Ontario,North York,Year,80000.0,80000.0,3596666

In [ ]:

review_ids = [
    15342796,
    15363720,
    15495035,
    15500205,
    15514769,
    15557280,
    15657440
]

technology_collection.loc[
    technology_collection["WIC_ID"].isin(review_ids),
    "Match_Status"
] = "Verified - Technology unavailable"


# Save progress
technology_collection.to_csv(
    "../data/processed/technology_collection.csv",
    index=False
)


print("UPDATED MATCH STATUS")

print(
    technology_collection[
        "Match_Status"
    ].value_counts()
)

UPDATED MATCH STATUS
Match_Status
Not checked                          15
Verified                             13
Verified - Technology unavailable     7
Verified - No technology listed       5
Needs verification                    1
Name: count, dtype: int64

In [ ]:

final_verification_queue = technology_collection[
    technology_collection["Match_Status"].isin(
        [
            "Not checked",
            "Needs verification"
        ]
    )
].copy()


final_verification_queue = (
    final_verification_queue
    .sort_values("Posting_Date")
    .reset_index(drop=True)
)


print("=" * 70)
print("FINAL VERIFICATION QUEUE")
print("=" * 70)

print(
    "\nJobs remaining:",
    len(final_verification_queue)
)


print("\nStatus breakdown:")

print(
    final_verification_queue[
        "Match_Status"
    ].value_counts()
)


display(
    final_verification_queue[
        [
            "WIC_ID",
            "Job_Title",
            "Posting_Date",
            "Province",
            "City",
            "Salary_Per",
            "Salary_Minimum",
            "Salary_Maximum",
            "Job_Bank_Job_Number",
            "Match_Status"
        ]
    ]
)

======================================================================
FINAL VERIFICATION QUEUE
======================================================================

Jobs remaining: 16

Status breakdown:
Match_Status
Not checked           15
Needs verification     1
Name: count, dtype: int64

,WIC_ID,Job_Title,Posting_Date,Province,City,Salary_Per,Salary_Minimum,Salary_Maximum,Job_Bank_Job_Number,Match_Status
0,15306899,data scientist,2026-03-06,Québec,NaN,Hour,46.15,46.15,3523161,Needs verification
1,15491326,business data analyst,2026-04-23,British Columbia,Burnaby,Hour,43.00,43.00,<NA>,Not checked
2,15566610,business data analyst,2026-05-20,Alberta,Edmonton,Hour,48.10,48.10,<NA>,Not checked
3,15597075,business intelligence specialist,2026-06-01,Ontario,Toronto,Hour,46.00,46.00,<NA>,Not checked
4,15604698,data analytics specialist,2026-06-03,Ontario,Toronto,Year,60000.00,75000.00,<NA>,Not checked
5,15628713,data scientist,2026-06-11,Ontario,Mississauga,Hour,45.00,55.00,<NA>,Not checked
6,15628476,business data analyst,2026-06-11,Alberta,Edmonton,Hour,46.00,48.00,<NA>,Not checked
7,15642551,data analytics specialist,2026-06-16,Ontario,NaN,Hour,35.00,35.00,<NA>,Not checked
8,15651841,data analyst - informatics and systems,2026-06-19,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00,<NA>,Not checked
9,15693882,data analyst - informatics and systems,2026-07-07,Québec,Stoneham-et-Tewkesbury,Hour,40.00,40.00,<NA>,Not checked
10,15730915,data scientist,2026-07-21,Saskatchewan,Saskatoon,Year,69880.00,94544.00,<NA>,Not checked
11,15746387,data scientist,2026-07-28,Québec,Laval,Hour,41.91,49.10,<NA>,Not checked
12,15747768,data scientist,2026-07-28,New Brunswick,Shediac,Hour,42.00,45.00,<NA>,Not checked
13,15749186,business intelligence specialist,2026-07-29,Québec,Montréal,Hour,36.00,36.00,<NA>,Not checked
14,15752280,data analytics specialist,2026-07-30,Québec,Mirabel,Year,79000.00,82000.00,<NA>,Not checked
15,15752279,data analytics specialist,2026-07-30,Québec,Montréal,Year,79000.00,82000.00,<NA>,Not checked

In [ ]:


add_job_match(
    wic_id=15306899,
    job_bank_number="3523161",
    job_bank_url="https://www.on.jobbank.gc.ca/jobsearch/jobposting/49056022",
    technologies=(
        "Jira; "
        "Machine Learning; "
        "Linux; "
        "C++; "
        "Linux - PSOS; "
        "MS Windows; "
        "Internet; "
        "Programming languages; "
        "Software development; "
        "Data analysis software"
    ),
    status="Verified"
)

save_technology_progress()


print("\nUPDATED MATCH STATUS")

print(
    technology_collection[
        "Match_Status"
    ].value_counts()
)

Progress saved!

MATCH STATUS
Match_Status
Not checked                          15
Verified                             14
Verified - Technology unavailable     7
Verified - No technology listed       5
Name: count, dtype: int64

UPDATED MATCH STATUS
Match_Status
Not checked                          15
Verified                             14
Verified - Technology unavailable     7
Verified - No technology listed       5
Name: count, dtype: int64

In [ ]:

import pandas as pd
from collections import Counter



verified_technology_jobs = technology_collection[
    technology_collection["Match_Status"].isin(
        [
            "Verified",
            "Verified - No technology listed"
        ]
    )
].copy()


print(
    "Verified postings used for technology analysis:",
    len(verified_technology_jobs)
)



technology_name_map = {

    # Cloud
    "Amazon Web Services (AWS)": "AWS",
    "Amazon Web Services": "AWS",

    # Microsoft
    "Microsoft Office": "MS Office",
    "MS Office": "MS Office",
    "Microsoft Excel": "Excel",
    "MS Excel": "Excel",
    "Microsoft Power BI": "Power BI",

    # Programming
    "Programming languages": "Programming Languages",
    "Programming software": "Programming Software",

    # Machine learning
    "Machine learning": "Machine Learning",

    # Data
    "Data analysis software": "Data Analysis Software",
    "Data Warehouse": "Data Warehouse",

    # Development
    "Software development": "Software Development",

    # Operating systems
    "MS Windows": "Windows",

    # Database
    "Database software": "Database Software",

    # Network
    "Networking software": "Networking Software",
    "Networking security": "Network Security",

    # Other
    "Spreadsheet": "Spreadsheet Software"
}



technology_rows = []


for _, row in verified_technology_jobs.iterrows():

    technology_text = row["Technology_Knowledge"]

    # Skip postings where Job Bank explicitly listed no technology
    if pd.isna(technology_text):
        continue

    technology_text = str(technology_text).strip()

    if technology_text == "":
        continue


    technologies = technology_text.split(";")


    # Avoid counting the same technology twice
    # within one job posting
    technologies_for_job = set()


    for technology in technologies:

        technology = technology.strip()

        if not technology:
            continue


        # Standardize names
        technology = technology_name_map.get(
            technology,
            technology
        )


        technologies_for_job.add(
            technology
        )


    for technology in technologies_for_job:

        technology_rows.append(
            {
                "WIC_ID": row["WIC_ID"],
                "Job_Title": row["Job_Title"],
                "Posting_Date": row["Posting_Date"],
                "Province": row["Province"],
                "Technology": technology
            }
        )



technology_mentions = pd.DataFrame(
    technology_rows
)


print(
    "\nTechnology mentions:",
    len(technology_mentions)
)


print(
    "Unique technologies:",
    technology_mentions["Technology"].nunique()
)



verified_denominator = len(
    verified_technology_jobs
)


technology_demand = (
    technology_mentions
    .groupby("Technology")["WIC_ID"]
    .nunique()
    .reset_index(
        name="Postings_Mentioning"
    )
)


technology_demand[
    "Demand_Percentage"
] = (

    technology_demand[
        "Postings_Mentioning"
    ]

    / verified_denominator

    * 100
).round(2)


technology_demand = (
    technology_demand
    .sort_values(
        [
            "Postings_Mentioning",
            "Technology"
        ],
        ascending=[
            False,
            True
        ]
    )
    .reset_index(drop=True)
)



print("\n" + "=" * 60)

print("FINAL TECHNOLOGY DEMAND")

print("=" * 60)

print(
    "\nDenominator:",
    verified_denominator,
    "verified direct Job Bank postings"
)


display(
    technology_demand.head(20)
)



technology_mentions.to_csv(
    "../data/processed/technology_mentions.csv",
    index=False
)


technology_demand.to_csv(
    "../data/processed/technology_demand.csv",
    index=False
)


verified_technology_jobs.to_csv(
    "../data/processed/verified_technology_jobs.csv",
    index=False
)


print("\nFILES SAVED:")

print(
    "technology_mentions.csv"
)

print(
    "technology_demand.csv"
)

print(
    "verified_technology_jobs.csv"
)

Verified postings used for technology analysis: 19

Technology mentions: 77
Unique technologies: 41

============================================================
FINAL TECHNOLOGY DEMAND
============================================================

Denominator: 19 verified direct Job Bank postings

,Technology,Postings_Mentioning,Demand_Percentage
0,Data Analysis Software,4,21.05
1,Data Warehouse,4,21.05
2,Linux,4,21.05
3,MySQL,4,21.05
4,Programming Software,4,21.05
5,Python,4,21.05
6,SASS,4,21.05
7,Machine Learning,3,15.79
8,SQL,3,15.79
9,Spreadsheet Software,3,15.79
10,AWS,2,10.53
11,Android,2,10.53
12,C++,2,10.53
13,Database Software,2,10.53
14,Java,2,10.53
15,MS Office,2,10.53
16,Mapping and data visualization software,2,10.53
17,Software Development,2,10.53
18,Windows,2,10.53
19,Agile,1,5.26

FILES SAVED:
technology_mentions.csv
technology_demand.csv
verified_technology_jobs.csv